export const villageois = [
  {
    serie: "3",
    nomFR: "apollon",
    nomEN: "apollo",
    style: ["fantaisie", "simple"],
    race: "aigles",
    caractere: "Versatile",
    anniversaire: "04/07",
    numero: "297",
    couleur: ["blanc", "orange", "gris"],
  },
  {
    serie: "5",
    nomFR: "astair",
    nomEN: "quinn",
    style: ["fantaisie", "élégant"],
    race: "aigles",
    caractere: "Grande soeur",
    anniversaire: "20/01",
    numero: "440",
    couleur: ["blanc", "rose", "violet"],
  },
  {
    serie: "1",
    nomFR: "aurelie",
    nomEN: "amelia",
    style: ["fantaisie", "élégant"],
    race: "aigles",
    caractere: "Arrogante",
    anniversaire: "19/11",
    numero: "075",
    couleur: ["rouge", "gris", "blanc", "noir"],
  },
  {
    serie: "2",
    nomFR: "enzo",
    nomEN: "keaton",
    style: ["magnifique", "fantaisie"],
    race: "aigles",
    caractere: "Chic",
    anniversaire: "01/06",
    numero: "193",
    couleur: ["turquoise", "jaune", "gris"],
  },
  {
    serie: "2",
    nomFR: "faust",
    nomEN: "avery",
    style: ["simple", "magnifique"],
    race: "aigles",
    caractere: "Versatile",
    anniversaire: "22/02",
    numero: "140",
    couleur: ["gris", "orange", "kaki"],
  },
  {
    serie: "4",
    nomFR: "garance",
    nomEN: "celia",
    style: ["élégant", "mimi"],
    race: "aigles",
    caractere: "Normale",
    anniversaire: "25/03",
    numero: "363",
    couleur: ["blanc", "vert", "jaune"],
  },
  {
    serie: "3",
    nomFR: "greggae",
    nomEN: "frank",
    style: ["magnifique", "fantaisie"],
    race: "aigles",
    couleur: "purple",
    caractere: "Versatile",
    anniversaire: "30/07",
    numero: "283",
    couleur: ["vert", "jaune"],
  },
  {
    serie: "1",
    nomFR: "manfred",
    nomEN: "sterling",
    style: ["simple", "élégant"],
    race: "aigles",
    caractere: "Sportif",
    anniversaire: "11/12",
    numero: "048",
    couleur: ["bleu", "blanc", "jaune"],
  },
  {
    serie: "4",
    nomFR: "napoléon",
    nomEN: "pierce",
    style: ["élégant", "actif"],
    race: "aigles",
    caractere: "Sportif",
    anniversaire: "08/01",
    numero: "336",
    couleur: ["blanc", "bleu", "jaune"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "phébus",
    nomEN: "buzz",
    style: ["simple", "actif"],
    race: "aigles",
    caractere: "Versatile",
    anniversaire: "07/12",
    numero: "WA-47",
    couleur: ["brun", "jaune"],
  },
  {
    serie: "1",
    nomFR: "allie",
    nomEN: "alli",
    style: ["magnifique", "élégant"],
    race: "alligators",
    caractere: "Arrogante",
    anniversaire: "08/11",
    numero: "036",
    couleur: ["turquoise", "rose", "blanc"],
  },
  {
    serie: "2",
    nomFR: "alphonse",
    nomEN: "alfonso",
    style: ["simple"],
    race: "alligators",
    caractere: "Paresseux",
    anniversaire: "09/06",
    numero: "153",
    couleur: ["brun", "blanc"],
  },
  {
    serie: "2",
    nomFR: "chuck",
    nomEN: "sly",
    style: ["fantaisie", "simple"],
    race: "alligators",
    caractere: "Sportif",
    anniversaire: "15/11",
    numero: "138",
    couleur: ["brun", "orange", "jaune"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "croko",
    nomEN: "boots",
    style: ["magnifique", "actif"],
    race: "alligators",
    caractere: "Sportif",
    anniversaire: "07/08",
    numero: "WA-34",
    couleur: ["vert", "blanc"],
  },
  {
    serie: "3",
    nomFR: "drago",
    nomEN: "drago",
    style: ["élégant", "magnifique"],
    race: "alligators",
    caractere: "Paresseux",
    anniversaire: "12/02",
    numero: "243",
    couleur: ["vert", "vert pastel"],
  },
  {
    serie: "3",
    nomFR: "hector",
    nomEN: "del",
    style: ["fantaisie", "simple"],
    race: "alligators",
    caractere: "Versatile",
    anniversaire: "27/05",
    numero: "223",
    couleur: ["bleu", "rouge"],
  },
  {
    serie: "4",
    nomFR: "odile",
    nomEN: "gayle",
    style: ["mimi"],
    race: "alligators",
    caractere: "Normale",
    anniversaire: "17/05",
    numero: "391",
    couleur: ["rose", "blanc", "fuchsia"],
  },
  {
    serie: "5",
    nomFR: "roswell",
    nomEN: "roswell",
    style: ["simple", "élégant"],
    race: "alligators",
    caractere: "Chic",
    anniversaire: "02/05",
    numero: "447",
    couleur: ["brun", "jaune pastel"],
  },
  {
    serie: "5",
    nomFR: "estrella",
    nomEN: "rio",
    style: ["fantaisie", "mimi"],
    race: "autruches",
    caractere: "Vive",
    anniversaire: "10/09",
    numero: "444",
    couleur: ["rouge", "vert", "multicolore"],
  },

  {
    serie: "2",
    nomFR: "faustine",
    nomEN: "phoebe",
    style: ["magnifique", "fantaisie"],
    race: "autruches",
    caractere: "Grande soeur",
    anniversaire: "22/04",
    numero: "135",
    couleur: ["jaune", "rouge", "multicolore"],
  },
  {
    serie: "4",
    nomFR: "gabin",
    nomEN: "cranston",
    style: ["simple", "fantaisie"],
    race: "autruches",
    caractere: "Paresseux",
    anniversaire: "23/09",
    numero: "392",
    couleur: ["blanc", "corail", "rouge"],
  },
  {
    serie: "2",
    nomFR: "gladys",
    nomEN: "gladys",
    style: ["élégant", "mimi"],
    race: "autruches",
    caractere: "Normale",
    anniversaire: "15/01",
    numero: "194",
    couleur: ["blanc", "noir", "rouge"],
  },

  {
    serie: "Welcome Amiibo",
    nomFR: "julie",
    nomEN: "julia",
    style: ["élégant", "magnifique"],
    race: "autruches",
    caractere: "Arrogante",
    anniversaire: "31/07",
    numero: "WA-29",
    couleur: ["vert", "bleu", "multicolore"],
  },

  {
    serie: "3",
    nomFR: "justine",
    nomEN: "flora",
    style: ["mimi", "actif"],
    race: "autruches",
    caractere: "Vive",
    anniversaire: "09/02",
    numero: "274",
    couleur: ["rose pastel", "fuchsia"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "laflèche",
    nomEN: "sprocket",
    style: ["simple", "actif"],
    race: "autruches",
    caractere: "Sportif",
    anniversaire: "01/12",
    numero: "WA-43",
    couleur: ["vert", "gris"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "ottie",
    nomEN: "sandy",
    style: ["simple", "fantaisie"],
    race: "autruches",
    caractere: "Normale",
    anniversaire: "21/10",
    numero: "WA-26",
    couleur: ["orange", "gris", "blanc"],
  },
  {
    serie: "1",
    nomFR: "phil",
    nomEN: "phil",
    style: ["élégant", "fantaisie"],
    race: "autruches",
    caractere: "Chic",
    anniversaire: "27/11",
    numero: "057",
    couleur: ["bleu", "rouge", "vert", "kaki"],
  },
  {
    serie: "4",
    nomFR: "reine",
    nomEN: "queenie",
    style: ["magnifique", "élégant"],
    race: "autruches",
    caractere: "Arrogante",
    anniversaire: "13/11",
    numero: "337",
    couleur: ["violet", "gris", "fuchsia", "rose"],
  },
  {
    serie: "3",
    nomFR: "sophie",
    nomEN: "blanche",
    style: ["élégant", "magnifique"],
    race: "autruches",
    caractere: "Arrogante",
    anniversaire: "21/12",
    numero: "262",
    couleur: ["blanc", "gris", "corail"],
  },
  {
    serie: "3",
    nomFR: "biquette",
    nomEN: "chevre",
    style: ["mimi", "élégant"],
    race: "boucs",
    caractere: "Normale",
    anniversaire: "06/03",
    numero: "242",
    couleur: ["blanc"],
  },
  {
    serie: "5",
    nomFR: "capri",
    nomEN: "sherb",
    style: ["simple", "mimi"],
    race: "boucs",
    caractere: "Paresseux",
    anniversaire: "18/01",
    numero: "425",
    couleur: ["bleu pastel", "bleu"],
  },
  {
    serie: "4",
    nomFR: "chavrina",
    nomEN: "pashmina",
    style: ["fantaisie", "élégant"],
    race: "boucs",
    caractere: "Grande soeur",
    anniversaire: "26/12",
    numero: "331",
    couleur: ["brun", "turquoise"],
  },
  {
    serie: "1",
    nomFR: "grognon",
    nomEN: "gruff",
    style: ["fantaisie", "magnifique"],
    race: "boucs",
    caractere: "Versatile",
    anniversaire: "29/08",
    numero: "066",
    couleur: ["vert", "brun"],
  },
  {
    serie: "2",
    nomFR: "moktar",
    nomEN: "kidd",
    style: ["élégant", "fantaisie"],
    race: "boucs",
    caractere: "Chic",
    anniversaire: "28/06",
    numero: "134",
    couleur: ["violet", "brun"],
  },
  {
    serie: "2",
    nomFR: "nana",
    nomEN: "nan",
    style: ["simple", "élégant"],
    race: "boucs",
    caractere: "Normale",
    anniversaire: "24/08",
    numero: "168",
    couleur: ["noir"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "seguin",
    nomEN: "billy",
    style: ["simple", "actif"],
    race: "boucs",
    caractere: "Sportif",
    anniversaire: "25/03",
    numero: "WA-20",
    couleur: ["orange", "brun", "jaune"],
  },
  {
    serie: "3",
    nomFR: "véra",
    nomEN: "velma",
    style: ["élégant", "magnifique"],
    race: "boucs",
    caractere: "Arrogante",
    anniversaire: "14/01",
    numero: "230",
    couleur: ["rose", "brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "bébert",
    nomEN: "weber",
    style: ["fantaisie, simple"],
    race: "canards",
    caractere: "Paresseux",
    anniversaire: "30/06",
    numero: "WA-35",
    couleur: ["brun"],
  },
  {
    serie: "3",
    nomFR: "caro",
    nomEN: "freckles",
    style: ["simple", "mimi"],
    race: "canards",
    caractere: "Vive",
    anniversaire: "19/02",
    numero: "236",
    couleur: ["rose", "rouge", "orange", "brun"],
  },
  {
    serie: "1",
    nomFR: "choco",
    nomEN: "bill",
    style: ["actif"],
    race: "canards",
    caractere: "Sportif",
    anniversaire: "01/02",
    numero: "033",
    couleur: ["marron", "orange"],
  },
  {
    serie: "2",
    nomFR: "colvert",
    nomEN: "drake",
    style: ["fantaisie, simple"],
    race: "canards",
    caractere: "Paresseux",
    anniversaire: "25/06",
    numero: "181",
    couleur: ["vert", "vert pastel"],
  },
  {
    serie: "4",
    nomFR: "déborah",
    nomEN: "gloria",
    style: ["magnifique", "élégant"],
    race: "canards",
    caractere: "Arrogante",
    anniversaire: "12/08",
    numero: "381",
    couleur: ["jaune pastel", "violet", "rose"],
  },
  {
    serie: "3",
    nomFR: "joseph",
    nomEN: "joey",
    style: ["simple"],
    race: "canards",
    caractere: "Paresseux",
    anniversaire: "03/01",
    numero: "266",
    couleur: ["orange"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "ketchup",
    nomEN: "ketchup",
    style: ["mimi"],
    race: "canards",
    caractere: "Vive",
    anniversaire: "27/07",
    numero: "WA-14",
    couleur: ["orange", "rouge", "vert"],
  },
  {
    serie: "4",
    nomFR: "maëlle",
    nomEN: "maelle",
    style: ["fantaisie", "simple"],
    race: "canards",
    caractere: "Arrogante",
    anniversaire: "08/04",
    numero: "388",
    couleur: ["orange", "rouge", "brun"],
  },
  {
    serie: "3",
    nomFR: "maëllis",
    nomEN: "miranda",
    style: ["élégant", "chic"],
    race: "canards",
    caractere: "Arrogante",
    anniversaire: "23/04",
    numero: "222",
    couleur: ["fuchsia", "orange", "rose"],
  },
  {
    serie: "4",
    nomFR: "mallory",
    nomEN: "mallary",
    style: ["fantaisie", "magnifique"],
    race: "canards",
    caractere: "Arrogante",
    anniversaire: "17/11",
    numero: "321",
    couleur: ["violet", "orange", "gris"],
  },
  {
    serie: "1",
    nomFR: "mina",
    nomEN: "deena",
    style: ["simple", "mimi"],
    race: "canards",
    caractere: "Normale",
    anniversaire: "27/06",
    numero: "054",
    couleur: ["kaki", "orange", "jaune"],
  },
  {
    serie: "1",
    nomFR: "molly",
    nomEN: "molly",
    style: ["mimi", "simple"],
    race: "canards",
    caractere: "Normale",
    anniversaire: "07/03",
    numero: "099",
    couleur: ["kaki", "brun", "orange"],
  },
  {
    serie: "1",
    nomFR: "narcisse",
    nomEN: "quillson",
    style: ["élégant", "fantaisie"],
    race: "canards",
    caractere: "Chic",
    anniversaire: "22/12",
    numero: "041",
    couleur: ["vert", "jaune"],
  },
  {
    serie: "4",
    nomFR: "pompon",
    nomEN: "pompom",
    style: ["mimi", "simple"],
    race: "canards",
    caractere: "Vive",
    anniversaire: "11/02",
    numero: "373",
    couleur: ["blanc", "brun", "orange"],
  },
  {
    serie: "3",
    nomFR: "prof",
    nomEN: "derwin",
    style: ["simple", "élégant"],
    race: "canards",
    caractere: "Paresseux",
    anniversaire: "25/05",
    numero: "298",
    couleur: ["bleu", "orange", "jaune"],
  },
  {
    serie: "2",
    nomFR: "scooter",
    nomEN: "scoot",
    style: ["actif", "simple"],
    race: "canards",
    caractere: "Sportif",
    anniversaire: "13/06",
    numero: "147",
    couleur: ["vert", "jaune"],
  },
  {
    serie: "2",
    nomFR: "terrine",
    nomEN: "pate",
    style: ["simple", "mimi"],
    race: "canards",
    caractere: "Vive",
    anniversaire: "23/02",
    numero: "131",
    couleur: ["bleu", "rose", "orange"],
  },
  {
    serie: "4",
    nomFR: "abraham",
    nomEN: "erik",
    style: ["simple"],
    race: "cerfs",
    caractere: "Paresseux",
    anniversaire: "27/07",
    numero: "334",
    couleur: ["marron", "brun", "beige"],
  },
  {
    serie: "1",
    nomFR: "bibi",
    nomEN: "fauna",
    style: ["simple", "mimi"],
    race: "cerfs",
    caractere: "Normale",
    anniversaire: "26/03",
    numero: "019",
    couleur: ["marron", "brun"],
  },
  {
    serie: "3",
    nomFR: "bichoune",
    nomEN: "deirdre",
    style: ["simple"],
    race: "cerfs",
    caractere: "Grande soeur",
    anniversaire: "04/05",
    numero: "240",
    couleur: ["marron", "gris"],
  },
  {
    serie: "4",
    nomFR: "boubou",
    nomEN: "bruce",
    style: ["fantaisie", "simple"],
    race: "cerfs",
    caractere: "Versatile",
    anniversaire: "26/05",
    numero: "389",
    couleur: ["turquoise", "bleu"],
  },
  {
    serie: "Sanrio",
    nomFR: "chelsea",
    nomEN: "chelsea",
    style: ["mimi", "magnifique"],
    race: "cerfs",
    caractere: "Normale",
    anniversaire: "18/01",
    numero: "S5",
    couleur: ["vert", "blanc", "rose"],
  },
  {
    serie: "1",
    nomFR: "didi",
    nomEN: "diana",
    style: ["élégant", "magnifique"],
    race: "cerfs",
    caractere: "Arrogante",
    anniversaire: "04/01",
    numero: "089",
    couleur: ["blanc", "violet pastel"],
  },
  {
    serie: "1",
    nomFR: "jon",
    nomEN: "lopez",
    style: ["magnifique"],
    race: "cerfs",
    caractere: "Chic",
    anniversaire: "20/08",
    numero: "027",
    couleur: ["orange", "bleu pastel", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "nacer",
    nomEN: "bam",
    style: ["actif", "simple"],
    race: "cerfs",
    caractere: "Sportif",
    anniversaire: "07/11",
    numero: "237",
    couleur: ["bleu"],
  },
  {
    serie: "2",
    nomFR: "régis",
    nomEN: "zell",
    style: ["fantaisie", "magnifique"],
    race: "cerfs",
    caractere: "Chic",
    anniversaire: "07/06",
    numero: "159",
    couleur: ["blanc", "marron", "noir"],
  },
  {
    serie: "2",
    nomFR: "rosanne",
    nomEN: "fuchsia",
    style: ["fantaisie"],
    race: "cerfs",
    caractere: "Grande soeur",
    anniversaire: "19/09",
    numero: "123",
    couleur: ["fuchsia", "jaune", "bleu"],
  },
  {
    serie: "5",
    nomFR: "shino",
    nomEN: "shino",
    style: ["élégant", "magnifique"],
    race: "cerfs",
    caractere: "Vive",
    anniversaire: "31/10",
    numero: "436",
    couleur: ["blanc", "jaune pastel", "corail"],
  },
  {
    serie: "2",
    nomFR: "stefaon",
    nomEN: "beau",
    style: ["simple", "mimi"],
    race: "cerfs",
    caractere: "Paresseux",
    anniversaire: "05/04",
    numero: "167",
    couleur: ["orange", "blanc"],
  },
  {
    serie: "2",
    nomFR: "câlin",
    nomEN: "kidCat",
    style: ["actif", "simple"],
    race: "chats",
    caractere: "Sportif",
    anniversaire: "01/08",
    numero: "197",
    couleur: ["blanc", "rouge", "bleu"],
  },
  {
    serie: "1",
    nomFR: "cédric",
    nomEN: "punchy",
    style: ["simple"],
    race: "chats",
    caractere: "Paresseux",
    anniversaire: "11/04",
    numero: "050",
    couleur: ["blanc", "noir"],
  },
  {
    serie: "1",
    nomFR: "kabuki",
    nomEN: "kabuki",
    style: ["simple"],
    race: "chats",
    caractere: "Versatile",
    anniversaire: "29/11",
    numero: "037",
    couleur: ["blanc", "rouge", "violet", "noir"],
  },
  {
    serie: "4",
    nomFR: "kat",
    nomEN: "katt",
    style: ["fantaisie"],
    race: "chats",
    caractere: "Grande soeur",
    anniversaire: "27/04",
    numero: "323",
    couleur: ["brun", "jaune"],
  },
  {
    serie: "1",
    nomFR: "kiki",
    nomEN: "kiki",
    style: ["simple"],
    race: "chats",
    caractere: "Normale",
    anniversaire: "08/10",
    numero: "034",
    couleur: ["noir", "violet"],
  },
  {
    serie: "2",
    nomFR: "kitty",
    nomEN: "kitty",
    style: ["élégant", "magnifique"],
    race: "chats",
    caractere: "Arrogante",
    anniversaire: "15/02",
    numero: "166",
    couleur: ["brun", "kaki", "bleu", "blanc"],
  },
  {
    serie: "4",
    nomFR: "linette",
    nomEN: "lolly",
    style: ["simple"],
    race: "chats",
    caractere: "Normale",
    anniversaire: "27/03",
    numero: "333",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "3",
    nomFR: "marine",
    nomEN: "tangy",
    style: ["simple", "mimi"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "17/06",
    numero: "244",
    couleur: ["orange", "vert"],
  },
  {
    serie: "2",
    nomFR: "maud",
    nomEN: "felicity",
    style: ["mimi"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "30/03",
    numero: "119",
    couleur: ["jaune pastel", "rouge"],
  },
  {
    serie: "3",
    nomFR: "mistigri",
    nomEN: "mitzi",
    style: ["simple"],
    race: "chats",
    caractere: "Normale",
    anniversaire: "25/09",
    numero: "226",
    couleur: ["jaune pastel", "bleu"],
  },
  {
    serie: "3",
    nomFR: "momo",
    nomEN: "moe",
    style: ["actif", "simple"],
    race: "chats",
    caractere: "Paresseux",
    anniversaire: "12/01",
    numero: "273",
    couleur: ["bleu", "blanc"],
  },
  {
    serie: "1",
    nomFR: "monique",
    nomEN: "monique",
    style: ["magnifique", "élégant"],
    race: "chats",
    caractere: "Arrogante",
    anniversaire: "30/09",
    numero: "058",
    couleur: ["jaune pastel"],
  },
  {
    serie: "2",
    nomFR: "neferti",
    nomEN: "ankha",
    style: ["magnifique", "simple"],
    race: "chats",
    caractere: "Arrogante",
    anniversaire: "22/09",
    numero: "188",
    couleur: ["vert", "jaune", "bleu"],
  },
  {
    serie: "2",
    nomFR: "olivia",
    nomEN: "olivia",
    style: ["fantaisie", "élégant"],
    race: "chats",
    caractere: "Arrogante",
    anniversaire: "03/02",
    numero: "143",
    couleur: ["blanc", "marron"],
  },
  {
    serie: "4",
    nomFR: "perle",
    nomEN: "purrl",
    style: ["fantaisie", "élégant"],
    race: "chats",
    caractere: "Arrogante",
    anniversaire: "29/05",
    numero: "361",
    couleur: ["blanc", "marron", "brun", "bleu"],
  },
  {
    serie: "5",
    nomFR: "raymond",
    nomEN: "raymond",
    style: ["élégant", "fantaisie"],
    race: "chats",
    caractere: "Chic",
    anniversaire: "01/10",
    numero: "431",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "1",
    nomFR: "robert",
    nomEN: "bob",
    style: ["simple", "mimi"],
    race: "chats",
    caractere: "Paresseux",
    anniversaire: "01/01",
    numero: "018",
    couleur: ["violet"],
  },
  {
    serie: "4",
    nomFR: "rosie",
    nomEN: "rosie",
    style: ["mimi"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "27/02",
    numero: "386",
    couleur: ["bleu"],
  },
  {
    serie: "4",
    nomFR: "rougepif",
    nomEN: "rudy",
    style: ["actif", "simple"],
    race: "chats",
    caractere: "Sportif",
    anniversaire: "20/12",
    numero: "344",
    couleur: ["blanc", "marron"],
  },
  {
    serie: "3",
    nomFR: "suzy",
    nomEN: "merry",
    style: ["mimi"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "29/06",
    numero: "252",
    couleur: ["beige", "brun"],
  },
  {
    serie: "3",
    nomFR: "tigri",
    nomEN: "tabby",
    style: ["actif", "fantaisie"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "13/08",
    numero: "220",
    couleur: ["orange", "noir"],
  },
  {
    serie: "2",
    nomFR: "tom",
    nomEN: "tom",
    style: ["fantaisie", "simple"],
    race: "chats",
    caractere: "Vive",
    anniversaire: "10/12",
    numero: "128",
    couleur: ["bleu", "blanc"],
  },
  {
    serie: "3",
    nomFR: "tupux",
    nomEN: "stinky",
    style: ["actif", "simple"],
    race: "chats",
    caractere: "Sportif",
    anniversaire: "17/08",
    numero: "259",
    couleur: ["kaki"],
  },
  {
    serie: "4",
    nomFR: "âne-lise",
    nomEN: "annalise",
    style: ["élégant", "actif"],
    race: "chevaux",
    caractere: "Arrogante",
    anniversaire: "02/12",
    numero: "367",
    couleur: ["marron"],
  },
  {
    serie: "1",
    nomFR: "anne",
    nomEN: "winnie",
    style: ["fantaisie", "simple"],
    race: "chevaux",
    caractere: "Vive",
    anniversaire: "31/01",
    numero: "046",
    couleur: ["blanc", "kaki"],
  },
  {
    serie: "4",
    nomFR: "bourrico",
    nomEN: "papi",
    style: ["simple"],
    race: "chevaux",
    caractere: "Paresseux",
    anniversaire: "10/01",
    numero: "358",
    couleur: ["blanc", "marron"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "cléa",
    nomEN: "cleo",
    style: ["mimi", "élégant"],
    race: "chevaux",
    caractere: "Arrogante",
    anniversaire: "09/02",
    numero: "WA-48",
    couleur: ["blanc", "violet"],
  },
  {
    serie: "3",
    nomFR: "daniel",
    nomEN: "buck",
    style: ["actif", "simple"],
    race: "chevaux",
    caractere: "Sportif",
    anniversaire: "04/04",
    numero: "268",
    couleur: ["vert", "kaki", "beige"],
  },
  {
    serie: "1",
    nomFR: "dorian",
    nomEN: "clyde",
    style: ["simple", "mimi"],
    race: "chevaux",
    caractere: "Paresseux",
    anniversaire: "01/05",
    numero: "068",
    couleur: ["vert", "blanc"],
  },
  {
    serie: "2",
    nomFR: "édouard",
    nomEN: "ed",
    style: ["magnifique", "élégant"],
    race: "chevaux",
    caractere: "Chic",
    anniversaire: "16/09",
    numero: "163",
    couleur: ["blanc", "turquoise"],
  },
  {
    serie: "5",
    nomFR: "jennifer",
    nomEN: "reneigh",
    style: ["fantaisie", "magnifique"],
    race: "chevaux",
    caractere: "Grande soeur",
    anniversaire: "04/06",
    numero: "432",
    couleur: ["marron", "rose pastel"],
  },
  {
    serie: "2",
    nomFR: "lico",
    nomEN: "julian",
    style: ["magnifique", "fantaisie"],
    race: "chevaux",
    caractere: "Chic",
    anniversaire: "15/03",
    numero: "173",
    couleur: ["turquoise", "blanc", "bleu"],
  },
  {
    serie: "4",
    nomFR: "martin",
    nomEN: "elmer",
    style: ["simple", "fantaisie"],
    race: "chevaux",
    caractere: "Paresseux",
    anniversaire: "05/10",
    numero: "350",
    couleur: ["marron", "gris"],
  },
  {
    serie: "4",
    nomFR: "prune",
    nomEN: "peaches",
    style: ["mimi", "simple"],
    race: "chevaux",
    caractere: "Normale",
    anniversaire: "28/11",
    numero: "325",
    couleur: ["blanc", "rose"],
  },
  {
    serie: "1",
    nomFR: "rosco",
    nomEN: "roscoe",
    style: ["fantaisie", "magnifique"],
    race: "chevaux",
    caractere: "Versatile",
    anniversaire: "16/06",
    numero: "078",
    couleur: ["noir", "gris"],
  },
  {
    serie: "2",
    nomFR: "savana",
    nomEN: "savannah",
    style: ["fantaisie", "simple"],
    race: "chevaux",
    caractere: "Normale",
    anniversaire: "25/01",
    numero: "133",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "3",
    nomFR: "tony",
    nomEN: "colton",
    style: ["magnifique", "élégant"],
    race: "chevaux",
    caractere: "Chic",
    anniversaire: "22/05",
    numero: "233",
    couleur: ["blanc", "jaune"],
  },
  {
    serie: "3",
    nomFR: "victoria",
    nomEN: "victoria",
    style: ["actif", "simple"],
    race: "chevaux",
    caractere: "Vive",
    anniversaire: "11/07",
    numero: "280",
    couleur: ["marron"],
  },
  {
    serie: "1",
    nomFR: "anna",
    nomEN: "cherry",
    style: ["fantaisie", "élégant"],
    race: "chiens",
    caractere: "Grande soeur",
    anniversaire: "11/05",
    numero: "077",
    couleur: ["rouge", "noir"],
  },
  {
    serie: "2",
    nomFR: "avril",
    nomEN: "butch",
    style: ["fantaisie", "simple"],
    race: "chiens",
    caractere: "Versatile",
    anniversaire: "01/11",
    numero: "155",
    couleur: ["brun", "marron"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "béa",
    nomEN: "bea",
    style: ["simple", "fantaisie"],
    race: "chiens",
    caractere: "Normale",
    anniversaire: "15/10",
    numero: "WA-31",
    couleur: ["brun", "marron"],
  },
  {
    serie: "1",
    nomFR: "bernardo",
    nomEN: "benjamin",
    style: ["simple"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "03/08",
    numero: "084",
    couleur: ["jaune", "beige", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "brutus",
    nomEN: "mac",
    style: ["actif", "fantaisie"],
    race: "chiens",
    caractere: "Sportif",
    anniversaire: "11/11",
    numero: "245",
    couleur: ["beige", "jaune pastel", "marron"],
  },
  {
    serie: "2",
    nomFR: "cookie",
    nomEN: "cookie",
    style: ["mimi"],
    race: "chiens",
    caractere: "Vive",
    anniversaire: "18/06",
    numero: "137",
    couleur: ["rose", "blanc"],
  },
  {
    serie: "3",
    nomFR: "crocket",
    nomEN: "biskit",
    style: ["magnifique", "simple"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "13/05",
    numero: "279",
    couleur: ["orange", "vert"],
  },
  {
    serie: "1",
    nomFR: "dalma",
    nomEN: "portia",
    style: ["élégant", "magnifique"],
    race: "chiens",
    caractere: "Arrogante",
    anniversaire: "25/10",
    numero: "021",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "5",
    nomFR: "foufou",
    nomEN: "frett",
    style: ["fantaisie", "actif"],
    race: "chiens",
    caractere: "Versatile",
    anniversaire: "30/10",
    numero: "445",
    couleur: ["jaune", "blanc"],
  },
  {
    serie: "1",
    nomFR: "george",
    nomEN: "walker",
    style: ["simple"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "10/06",
    numero: "100",
    couleur: ["noir", "blanc"],
  },
  {
    serie: "2",
    nomFR: "ismaël",
    nomEN: "marcel",
    style: ["simple", "fantaisie"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "31/12",
    numero: "191",
    couleur: ["noir", "blanc"],
  },
  {
    serie: "4",
    nomFR: "mehdi",
    nomEN: "shep",
    style: ["simple", "fantaisie"],
    race: "chiens",
    caractere: "Chic",
    anniversaire: "24/11",
    numero: "332",
    couleur: ["gris", "beige", "kaki"],
  },
  {
    serie: "4",
    nomFR: "mirza",
    nomEN: "goldie",
    style: ["simple", "mimi"],
    race: "chiens",
    caractere: "Normale",
    anniversaire: "27/12",
    numero: "317",
    couleur: ["beige", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "naomie",
    nomEN: "daisy",
    style: ["simple", "mimi"],
    race: "chiens",
    caractere: "Normale",
    anniversaire: "16/11",
    numero: "258",
    couleur: ["jaune pastel", "gris"],
  },
  {
    serie: "4",
    nomFR: "nonos",
    nomEN: "bones",
    style: ["simple", "mimi"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "04/08",
    numero: "342",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "olympe",
    nomEN: "maddie",
    style: ["simple", "mimi"],
    race: "chiens",
    caractere: "Vive",
    anniversaire: "11/01",
    numero: "WA-19",
    couleur: ["brun", "marron"],
  },
  {
    serie: "4",
    nomFR: "ramsès",
    nomEN: "lucky",
    style: ["simple"],
    race: "chiens",
    caractere: "Paresseux",
    anniversaire: "04/11",
    numero: "385",
    couleur: ["blanc", "noir"],
  },

  {
    serie: "2",
    nomFR: "aaron",
    nomEN: "chops",
    style: ["magnifique", "élégant"],
    race: "cochons",
    caractere: "Chic",
    anniversaire: "13/10",
    numero: "185",
    couleur: ["vert pastel", "kaki", "brun"],
  },
  {
    serie: "2",
    nomFR: "bonno",
    nomEN: "hugh",
    style: ["simple", "actif"],
    race: "cochons",
    caractere: "Paresseux",
    anniversaire: "30/12",
    numero: "178",
    couleur: ["bleu"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "boris",
    nomEN: "boris",
    style: ["fantaisie", "élégant"],
    race: "cochons",
    caractere: "Versatile",
    anniversaire: "06/11",
    numero: "WA-11",
    couleur: ["bleu"],
  },
  {
    serie: "3",
    nomFR: "camille",
    nomEN: "gala",
    style: ["mimi", "élégant"],
    race: "cochons",
    caractere: "Normale",
    anniversaire: "05/03",
    numero: "265",
    couleur: ["rose"],
  },
  {
    serie: "4",
    nomFR: "jean-Bon",
    nomEN: "kevin",
    style: ["actif, simple"],
    race: "cochons",
    caractere: "Sportif",
    anniversaire: "26/04",
    numero: "380",
    couleur: ["orange"],
  },
  {
    serie: "3",
    nomFR: "justin",
    nomEN: "spork",
    style: ["simple, actif"],
    race: "cochons",
    caractere: "Paresseux",
    anniversaire: "03/09",
    numero: "235",
    couleur: ["beige", "jaune"],
  },
  {
    serie: "4",
    nomFR: "lucie",
    nomEN: "lucy",
    style: ["mimi", "élégant"],
    race: "cochons",
    caractere: "Normale",
    anniversaire: "02/06",
    numero: "349",
    couleur: ["blanc", "rose", "marron"],
  },
  {
    serie: "1",
    nomFR: "lydie",
    nomEN: "pancetti",
    style: ["mimi", "magnifique"],
    race: "cochons",
    caractere: "Arrogante",
    anniversaire: "14/11",
    numero: "085",
    couleur: ["brun", "jaune"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "marjorie",
    nomEN: "maggie",
    style: ["mimi", "élégant"],
    race: "cochons",
    caractere: "Normale",
    anniversaire: "03/09",
    numero: "WA-23",
    couleur: ["jaune", "orange"],
  },
  {
    serie: "2",
    nomFR: "pansy",
    nomEN: "agnes",
    style: ["simple", "élégant"],
    race: "cochons",
    caractere: "Grande soeur",
    anniversaire: "21/04",
    numero: "172",
    couleur: ["noir", "blanc"],
  },
  {
    serie: "1",
    nomFR: "porken",
    nomEN: "cobb",
    style: ["simple", "actif"],
    race: "cochons",
    caractere: "Sportif",
    anniversaire: "07/10",
    numero: "074",
    couleur: ["vert"],
  },
  {
    serie: "4",
    nomFR: "rose",
    nomEN: "peggy",
    style: ["mimi", "actif"],
    race: "cochons",
    caractere: "Vive",
    anniversaire: "23/05",
    numero: "365",
    couleur: ["beige", "brun", "marron"],
  },
  {
    serie: "1",
    nomFR: "salami",
    nomEN: "rasher",
    style: ["fantaisie", "simple"],
    race: "cochons",
    caractere: "Versatile",
    anniversaire: "07/04",
    numero: "029",
    couleur: ["marron"],
  },
  {
    serie: "3",
    nomFR: "tirbou",
    nomEN: "curly",
    style: ["simple", "actif"],
    race: "cochons",
    caractere: "Sportif",
    anniversaire: "26/07",
    numero: "288",
    couleur: ["rose"],
  },

  {
    serie: "1",
    nomFR: "trufa",
    nomEN: "truffles",
    style: ["mimi, magnifique"],
    race: "cochons",
    caractere: "Vive",
    anniversaire: "28/07",
    numero: "079",
    couleur: ["violet pastel", "rose"],
  },
  {
    serie: "1",
    nomFR: "amande",
    nomEN: "mint",
    style: ["magnifique", "mimi"],
    race: "écureuils",
    caractere: "Arrogante",
    anniversaire: "02/05",
    numero: "063",
    couleur: ["vert"],
  },
  {
    serie: "2",
    nomFR: "cachou",
    nomEN: "blaire",
    style: ["magnifique", "élégant"],
    race: "écureuils",
    caractere: "Arrogante",
    anniversaire: "03/07",
    numero: "139",
    couleur: ["gris", "blanc", "jaune pastel", "beige"],
  },
  {
    serie: "4",
    nomFR: "célia",
    nomEN: "cally",
    style: ["mimi", "élégant"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "04/09",
    numero: "395",
    couleur: ["kaki", "noir", "rouge"],
  },
  {
    serie: "4",
    nomFR: "damia",
    nomEN: "sally",
    style: ["simple", "élégant"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "19/06",
    numero: "371",
    couleur: ["orange", "marron"],
  },
  {
    serie: "4",
    nomFR: "électro",
    nomEN: "static",
    style: ["fantaisie", "actif"],
    race: "écureuils",
    caractere: "Versatile",
    anniversaire: "09/07",
    numero: "362",
    couleur: ["violet", "vert"],
  },
  {
    serie: "2",
    nomFR: "filibert",
    nomEN: "filbert",
    style: ["simple", "mimi"],
    race: "écureuils",
    caractere: "Paresseux",
    anniversaire: "03/06",
    numero: "165",
    couleur: ["bleu"],
  },
  {
    serie: "1",
    nomFR: "irène",
    nomEN: "poppy",
    style: ["mimi", "élégant"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "05/08",
    numero: "052",
    couleur: ["beige", "marron"],
  },
  {
    serie: "3",
    nomFR: "isabelle",
    nomEN: "caroline",
    style: ["mimi", "magnifique"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "15/07",
    numero: "290",
    couleur: ["rouge", "jaune"],
  },
  {
    serie: "4",
    nomFR: "lola",
    nomEN: "nibbles",
    style: ["mimi", "actif"],
    race: "écureuils",
    caractere: "Vive",
    anniversaire: "19/07",
    numero: "379",
    couleur: ["vert", "jaune"],
  },
  {
    serie: "3",
    nomFR: "mathéo",
    nomEN: "marshal",
    style: ["élégant", "fantaisie"],
    race: "écureuils",
    caractere: "Chic",
    anniversaire: "29/09",
    numero: "264",
    couleur: ["beige", "brun", "kaki"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "mounia",
    nomEN: "sylvana",
    style: ["mimi", "simple"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "22/10",
    numero: "WA-10",
    couleur: ["brun", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "nadeige",
    nomEN: "tasha",
    style: ["élégant", "magnifique"],
    race: "écureuils",
    caractere: "Arrogante",
    anniversaire: "30/11",
    numero: "WA-50",
    couleur: ["bleu", "blanc", "noir"],
  },
  {
    serie: "2",
    nomFR: "ninjette",
    nomEN: "agentS",
    style: ["actif", "simple"],
    race: "écureuils",
    caractere: "Vive",
    anniversaire: "02/07",
    numero: "198",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "3",
    nomFR: "pamela",
    nomEN: "hazel",
    style: ["actif", "mimi"],
    race: "écureuils",
    caractere: "Grande soeur",
    anniversaire: "30/08",
    numero: "248",
    couleur: ["brun", "marron"],
  },
  {
    serie: "2",
    nomFR: "pécan",
    nomEN: "pecan",
    style: ["élégant", "magnifique"],
    race: "écureuils",
    caractere: "Arrogante",
    anniversaire: "10/09",
    numero: "180",
    couleur: ["jaune pastel", "marron"],
  },
  {
    serie: "1",
    nomFR: "rachida",
    nomEN: "peanut",
    style: ["mimi"],
    race: "écureuils",
    caractere: "Vive",
    anniversaire: "08/06",
    numero: "095",
    couleur: ["fuchsia"],
  },

  {
    serie: "3",
    nomFR: "rocky",
    nomEN: "ricky",
    style: ["fantaisie", "simple"],
    race: "écureuils",
    caractere: "Versatile",
    anniversaire: "14/09",
    numero: "239",
    couleur: ["beige", "bleu"],
  },

  {
    serie: "1",
    nomFR: "roy",
    nomEN: "sheldon",
    style: ["actif", "fantaisie"],
    race: "écureuils",
    caractere: "Sportif",
    anniversaire: "26/02",
    numero: "031",
    couleur: ["jaune", "beige"],
  },
  {
    serie: "5",
    nomFR: "terra",
    nomEN: "ione",
    style: ["fantaisie", "mimi"],
    race: "écureuils",
    caractere: "Normale",
    anniversaire: "11/09",
    numero: "434",
    couleur: ["bleu", "bleu pastel", "vert pastel"],
  },
  {
    serie: "1",
    nomFR: "axel",
    nomEN: "axel",
    style: ["actif", "simple"],
    race: "éléphants",
    caractere: "Sportif",
    anniversaire: "23/03",
    numero: "090",
    couleur: ["bleu"],
  },
  {
    serie: "3",
    nomFR: "barry",
    nomEN: "tucker",
    style: ["actif", "simple"],
    race: "éléphants",
    caractere: "Paresseux",
    anniversaire: "07/09",
    numero: "261",
    couleur: ["beige", "brun"],
  },

  {
    serie: "Sanrio",
    nomFR: "chaï",
    nomEN: "chai",
    style: ["mimi", "élégant"],
    race: "éléphants",
    caractere: "Vive",
    anniversaire: "06/03",
    numero: "S4",
    couleur: ["bleu pastel", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "ella",
    nomEN: "ellie",
    style: ["simple", "mimi"],
    race: "éléphants",
    caractere: "Normale",
    anniversaire: "12/05",
    numero: "WA-33",
    couleur: ["brun", "rose", "beige"],
  },
  {
    serie: "3",
    nomFR: "éloïse",
    nomEN: "eloise",
    style: ["élégant, simple"],
    race: "éléphants",
    caractere: "Arrogante",
    anniversaire: "08/12",
    numero: "246",
    couleur: ["jaune", "marron"],
  },
  {
    serie: "2",
    nomFR: "fanny",
    nomEN: "tia",
    style: ["mimi", "élégant"],
    race: "éléphants",
    caractere: "Normale",
    anniversaire: "18/11",
    numero: "121",
    couleur: ["blanc", "bleu"],
  },
  {
    serie: "4",
    nomFR: "maguy",
    nomEN: "margie",
    style: ["élégant", "mimi"],
    race: "éléphants",
    caractere: "Normale",
    anniversaire: "28/01",
    numero: "384",
    couleur: ["blanc", "jaune", "rouge"],
  },
  {
    serie: "2",
    nomFR: "miles",
    nomEN: "bigTop",
    style: ["simple", "actif"],
    race: "éléphants",
    caractere: "Paresseux",
    anniversaire: "03/10",
    numero: "199",
    couleur: ["gris"],
  },
  {
    serie: "1",
    nomFR: "opaline",
    nomEN: "opal",
    style: ["élégant", "fantaisie"],
    race: "éléphants",
    caractere: "Arrogante",
    anniversaire: "20/01",
    numero: "051",
    couleur: ["vert"],
  },
  {
    serie: "4",
    nomFR: "pachy",
    nomEN: "dizzy",
    style: ["simple"],
    race: "éléphants",
    caractere: "Paresseux",
    anniversaire: "14/07",
    numero: "326",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "paolo",
    nomEN: "paolo",
    style: ["simple", "élégant"],
    race: "éléphants",
    caractere: "Paresseux",
    anniversaire: "05/05",
    numero: "WA-05",
    couleur: ["fuchsia", "blanc"],
  },
  {
    serie: "5",
    nomFR: "punk",
    nomEN: "cyd",
    style: ["fantaisie", "actif"],
    race: "éléphants",
    caractere: "Versatile",
    anniversaire: "09/06",
    numero: "429",
    couleur: ["rouge", "noir"],
  },

  {
    serie: "4",
    nomFR: "anabelle",
    nomEN: "anabelle",
    style: ["mimi", "simple"],
    race: "fourmiliers",
    caractere: "Vive",
    anniversaire: "16/02",
    numero: "343",
    couleur: ["jaune pastel", "jaune", "orange"],
  },
  {
    serie: "3",
    nomFR: "antonio",
    nomEN: "antonio",
    style: ["simple"],
    race: "fourmiliers",
    caractere: "Sportif",
    anniversaire: "20/10",
    numero: "295",
    couleur: ["beige", "gris", "noir", "blanc"],
  },
  {
    serie: "4",
    nomFR: "blair",
    nomEN: "olaf",
    style: ["mimi", "simple"],
    race: "fourmiliers",
    caractere: "Normale",
    anniversaire: "10/05",
    numero: "348",
    couleur: ["brun", "noir", "gris"],
  },
  {
    serie: "5",
    nomFR: "cléo",
    nomEN: "zoe",
    style: ["mimi", "simple"],
    race: "fourmiliers",
    caractere: "Normale",
    anniversaire: "10/02",
    numero: "442",
    couleur: ["turquoise", "beige", "orange"],
  },
  {
    serie: "1",
    nomFR: "cyrano",
    nomEN: "cyrano",
    style: ["fantaisie", "actif"],
    race: "fourmiliers",
    caractere: "Versatile",
    anniversaire: "09/03",
    numero: "094",
    couleur: ["orange", "bleu"],
  },
  {
    serie: "2",
    nomFR: "mathilda",
    nomEN: "pango",
    style: ["élégant", "fantaisie"],
    race: "fourmiliers",
    caractere: "Vive",
    anniversaire: "09/11",
    numero: "192",
    couleur: ["vert", "bleu"],
  },
  {
    serie: "1",
    nomFR: "robertaa",
    nomEN: "annalisa",
    style: ["élégant", "magnifique"],
    race: "fourmiliers",
    caractere: "Normale",
    anniversaire: "06/02",
    numero: "083",
    couleur: ["blanc", "noir", "rouge"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "tarina",
    nomEN: "snooty",
    style: ["simple"],
    race: "fourmiliers",
    caractere: "Arrogante",
    anniversaire: "24/10",
    numero: "WA-44",
    couleur: ["rose", "violet"],
  },

  {
    serie: "4",
    nomFR: "babouin",
    nomEN: "boone",
    style: ["élégant", "fantaisie"],
    race: "gorilles",
    caractere: "Sportif",
    anniversaire: "12/09",
    numero: "328",
    couleur: ["brun", "gris", "blanc"],
  },
  {
    serie: "2",
    nomFR: "césar",
    nomEN: "cesar",
    style: ["fantaisie", "élégant"],
    race: "gorilles",
    caractere: "Versatile",
    anniversaire: "06/09",
    numero: "144",
    couleur: ["noir", "orange"],
  },
  {
    serie: "3",
    nomFR: "gaëlle",
    nomEN: "violet",
    style: ["magnifique", "fantaisie"],
    race: "gorilles",
    caractere: "Arrogante",
    anniversaire: "01/09",
    numero: "282",
    couleur: ["rose", "violet"],
  },
  {
    serie: "2",
    nomFR: "gertrude",
    nomEN: "rocket",
    style: ["actif", "fantaisie"],
    race: "gorilles",
    caractere: "Grande soeur",
    anniversaire: "14/04",
    numero: "200",
    couleur: ["brun", "beige"],
  },
  {
    serie: "4",
    nomFR: "gogo",
    nomEN: "peewee",
    style: ["actif", "fantaisie"],
    race: "gorilles",
    caractere: "Versatile",
    anniversaire: "11/09",
    numero: "346",
    couleur: ["gris", "bleu"],
  },
  {
    serie: "1",
    nomFR: "gustave",
    nomEN: "al",
    style: ["actif"],
    race: "gorilles",
    caractere: "Paresseux",
    anniversaire: "18/10",
    numero: "025",
    couleur: ["vert", "noir"],
  },
  {
    serie: "3",
    nomFR: "loran",
    nomEN: "hans",
    style: ["élégant", "magnifique"],
    race: "gorilles",
    caractere: "Chic",
    anniversaire: "05/12",
    numero: "241",
    couleur: ["bleu", "gris", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "louis",
    nomEN: "louie",
    style: ["actif", "simple"],
    race: "gorilles",
    caractere: "Sportif",
    anniversaire: "26/03",
    numero: "WA-30",
    couleur: ["beige", "marron", "brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "primo",
    nomEN: "boyd",
    style: ["simple", "fantaisie"],
    race: "gorilles",
    caractere: "Versatile",
    anniversaire: "01/10",
    numero: "WA-21",
    couleur: ["rouge", "beige", "brun"],
  },
  {
    serie: "Sanrio",
    nomFR: "rilla",
    nomEN: "rilla",
    style: ["mimi", "élégant"],
    race: "gorilles",
    caractere: "Vive",
    anniversaire: "01/11",
    numero: "S1",
    couleur: ["rose pastel", "rose", "jaune"],
  },

  {
    serie: "Welcome Amiibo",
    nomFR: "bajoue",
    nomEN: "huck",
    style: ["simple", "fantaisie"],
    race: "grenouilles",
    caractere: "Chic",
    anniversaire: "09/07",
    numero: "WA-09",
    couleur: ["gris", "jaune"],
  },
  {
    serie: "4",
    nomFR: "carlos",
    nomEN: "croque",
    style: ["élégant", "fantaisie"],
    race: "grenouilles",
    caractere: "Versatile",
    anniversaire: "18/07",
    numero: "330",
    couleur: ["orange", "jaune", "blanc"],
  },
  {
    serie: "4",
    nomFR: "crabot",
    nomEN: "ribbot",
    style: ["simple", "actif"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "13/02",
    numero: "366",
    couleur: ["gris", "noir"],
  },
  {
    serie: "3",
    nomFR: "crakos",
    nomEN: "wartJr",
    style: ["simple"],
    race: "grenouilles",
    caractere: "Versatile",
    anniversaire: "21/08",
    numero: "247",
    couleur: ["brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "fabien",
    nomEN: "raddle",
    style: ["élégant", "simple"],
    race: "grenouilles",
    caractere: "Paresseux",
    anniversaire: "06/06",
    numero: "WA-28",
    couleur: ["gris", "noir", "jaune"],
  },
  {
    serie: "3",
    nomFR: "figaro",
    nomEN: "cousteau",
    style: ["élégant", "magnifique"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "17/12",
    numero: "229",
    couleur: ["jaune", "brun", "orange"],
  },
  {
    serie: "1",
    nomFR: "gambette",
    nomEN: "jambette",
    style: ["élégant", "magnifique"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "17/10",
    numero: "028",
    couleur: ["vert"],
  },
  {
    serie: "1",
    nomFR: "gloria",
    nomEN: "gigi",
    style: ["magnifique", "élégant"],
    race: "grenouilles",
    caractere: "Arrogante",
    anniversaire: "11/08",
    numero: "040",
    couleur: ["violet", "jaune", "blanc", "gris"],
  },
  {
    serie: "2",
    nomFR: "gordon",
    nomEN: "drift",
    style: ["simple", "actif"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "09/10",
    numero: "189",
    couleur: ["rouge", "orange", "jaune", "marron"],
  },
  {
    serie: "1",
    nomFR: "henri",
    nomEN: "henry",
    style: ["fantaisie", "simple"],
    race: "grenouilles",
    caractere: "Chic",
    anniversaire: "21/09",
    numero: "092",
    couleur: ["vert", "orange"],
  },
  {
    serie: "1",
    nomFR: "jérémie",
    nomEN: "jeremiah",
    style: ["simple"],
    race: "grenouilles",
    caractere: "Paresseux",
    anniversaire: "08/07",
    numero: "076",
    couleur: ["bleu"],
  },
  {
    serie: "2",
    nomFR: "milos",
    nomEN: "camofrog",
    style: ["fantaisie", "actif"],
    race: "grenouilles",
    caractere: "Versatile",
    anniversaire: "05/06",
    numero: "183",
    couleur: ["camo", "vert", "brun", "beige"],
  },
  {
    serie: "2",
    nomFR: "prince",
    nomEN: "prince",
    style: ["simple", "actif"],
    race: "grenouilles",
    caractere: "Paresseux",
    anniversaire: "21/07",
    numero: "130",
    couleur: ["vert"],
  },
  {
    serie: "3",
    nomFR: "raina",
    nomEN: "lily",
    style: ["mimi", "simple"],
    race: "grenouilles",
    caractere: "Normale",
    anniversaire: "04/02",
    numero: "218",
    couleur: ["vert", "jaune pastel", "corail"],
  },
  {
    serie: "4",
    nomFR: "rénata",
    nomEN: "puddles",
    style: ["mimi", "magnifique"],
    race: "grenouilles",
    caractere: "Vive",
    anniversaire: "13/01",
    numero: "351",
    couleur: ["rose", "fuchsia"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "rénato",
    nomEN: "tad",
    style: ["actif", "simple"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "03/08",
    numero: "WA-40",
    couleur: ["vert"],
  },
  {
    serie: "4",
    nomFR: "verbert",
    nomEN: "frobert",
    style: ["actif", "simple"],
    race: "grenouilles",
    caractere: "Sportif",
    anniversaire: "08/02",
    numero: "393",
    couleur: ["vert", "noir"],
  },
  {
    serie: "3",
    nomFR: "violette",
    nomEN: "diva",
    style: ["magnifique", "élégant"],
    race: "grenouilles",
    caractere: "Grande soeur",
    anniversaire: "02/10",
    numero: "256",
    couleur: ["violet"],
  },

  {
    serie: "2",
    nomFR: "charles",
    nomEN: "hamphrey",
    style: ["fantaisie", "simple"],
    race: "hamsters",
    caractere: "Versatile",
    anniversaire: "25/02",
    numero: "195",
    couleur: ["noir", "bleu", "gris"],
  },
  {
    serie: "2",
    nomFR: "chico",
    nomEN: "rodney",
    style: ["magnifique", "fantaisie"],
    race: "hamsters",
    caractere: "Chic",
    anniversaire: "10/11",
    numero: "146",
    couleur: ["bleu", "turquoise", "beige", "rose"],
  },
  {
    serie: "1",
    nomFR: "emma",
    nomEN: "flurry",
    style: ["élégant", "mimi"],
    race: "hamsters",
    caractere: "Normale",
    anniversaire: "30/01",
    numero: "067",
    couleur: ["blanc", "bleu pastel"],
  },
  {
    serie: "4",
    nomFR: "esther",
    nomEN: "apple",
    style: ["mimi", "simple"],
    race: "hamsters",
    caractere: "Vive",
    anniversaire: "24/09",
    numero: "359",
    couleur: ["rose", "rouge", "blanc"],
  },
  {
    serie: "4",
    nomFR: "graham",
    nomEN: "graham",
    style: ["simple", "fantaisie"],
    race: "hamsters",
    caractere: "Chic",
    anniversaire: "20/06",
    numero: "324",
    couleur: ["jaune", "blanc", "vert"],
  },
  {
    serie: "1",
    nomFR: "guido",
    nomEN: "clay",
    style: ["élégant", "simple"],
    race: "hamsters",
    caractere: "Paresseux",
    anniversaire: "19/10",
    numero: "088",
    couleur: ["brun", "marron", "orange", "beige"],
  },
  {
    serie: "3",
    nomFR: "jojo",
    nomEN: "hamlet",
    style: ["simple", "actif"],
    race: "hamsters",
    caractere: "Sportif",
    anniversaire: "30/05",
    numero: "275",
    couleur: ["orange", "beige", "jaune"],
  },
  {
    serie: "5",
    nomFR: "marlou",
    nomEN: "marlo",
    style: ["fantaisie", "magnifique"],
    race: "hamsters",
    caractere: "Versatile",
    anniversaire: "26/06",
    numero: "437",
    couleur: ["noir", "gris", "blanc"],
  },
  {
    serie: "3",
    nomFR: "stella",
    nomEN: "soleil",
    style: ["fantaisie", "magnifique"],
    race: "hamsters",
    caractere: "Arrogante",
    anniversaire: "09/08",
    numero: "296",
    couleur: ["orange", "beige", "vert pastel"],
  },

  {
    serie: "4",
    nomFR: "bebel",
    nomEN: "rocco",
    style: ["simple", "fantaisie"],
    race: "hippopotames",
    caractere: "Versatile",
    anniversaire: "18/08",
    numero: "322",
    couleur: ["vert", "beige"],
  },
  {
    serie: "1",
    nomFR: "bertha",
    nomEN: "bertha",
    style: ["mimi", "élégant"],
    race: "hippopotames",
    caractere: "Normale",
    anniversaire: "25/04",
    numero: "093",
    couleur: ["turquoise", "bleu", "beige"],
  },
  {
    serie: "1",
    nomFR: "biff",
    nomEN: "biff",
    style: ["magnifique", "actif"],
    race: "hippopotames",
    caractere: "Sportif",
    anniversaire: "29/03",
    numero: "070",
    couleur: ["marron", "beige"],
  },
  {
    serie: "2",
    nomFR: "bob",
    nomEN: "harry",
    style: ["fantaisie", "simple"],
    race: "hippopotames",
    caractere: "Versatile",
    anniversaire: "07/01",
    numero: "124",
    couleur: ["beige", "brun", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "hippy",
    nomEN: "bubbles",
    style: ["actif", "mimi"],
    race: "hippopotames",
    caractere: "Vive",
    anniversaire: "18/09",
    numero: "228",
    couleur: ["brun", "marron", "beige"],
  },
  {
    serie: "4",
    nomFR: "paulito",
    nomEN: "hippeux",
    style: ["élégant", "magnifique"],
    race: "hippopotames",
    caractere: "Chic",
    anniversaire: "15/10",
    numero: "383",
    couleur: ["vert", "vert pastel", "brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "potama",
    nomEN: "bitty",
    style: ["mimi", "élégant"],
    race: "hippopotames",
    caractere: "Arrogante",
    anniversaire: "06/10",
    numero: "WA-22",
    couleur: ["rose"],
  },

  {
    serie: "Welcome Amiibo",
    nomFR: "kanga",
    nomEN: "carrie",
    style: ["mimi"],
    race: "kangourous",
    caractere: "Normale",
    anniversaire: "05/12",
    numero: "WA-13",
    couleur: ["brun"],
  },
  {
    serie: "4",
    nomFR: "madsie",
    nomEN: "sylvia",
    style: ["simple", "magnifique"],
    race: "kangourous",
    caractere: "Grande soeur",
    anniversaire: "03/05",
    numero: "369",
    couleur: ["violet"],
  },
  {
    serie: "2",
    nomFR: "mathilde",
    nomEN: "mathilda",
    style: ["fantaisie", "magnifique"],
    race: "kangourous",
    caractere: "Arrogante",
    anniversaire: "12/11",
    numero: "162",
    couleur: ["noir", "blanc", "violet"],
  },
  {
    serie: "3",
    nomFR: "mike",
    nomEN: "rooney",
    style: ["actif"],
    race: "kangourous",
    caractere: "Versatile",
    anniversaire: "01/12",
    numero: "270",
    couleur: ["turquoise", "brun", "noir"],
  },
  {
    serie: "2",
    nomFR: "poquette",
    nomEN: "kitt",
    style: ["élégant", "simple"],
    race: "kangourous",
    caractere: "Normale",
    anniversaire: "11/10",
    numero: "127",
    couleur: ["kaki", "jaune pastel", "beige"],
  },
  {
    serie: "3",
    nomFR: "rhona",
    nomEN: "astrid",
    style: ["fantaisie", "actif"],
    race: "kangourous",
    caractere: "Arrogante",
    anniversaire: "08/09",
    numero: "276",
    couleur: ["blanc", "beige", "brun"],
  },
  {
    serie: "1",
    nomFR: "selma",
    nomEN: "marcie",
    style: ["mimi", "élégant"],
    race: "kangourous",
    caractere: "Normale",
    anniversaire: "31/05",
    numero: "042",
    couleur: ["rose", "violet"],
  },
  {
    serie: "4",
    nomFR: "walt",
    nomEN: "walt",
    style: ["fantaisie"],
    race: "kangourous",
    caractere: "Versatile",
    anniversaire: "24/04",
    numero: "354",
    couleur: ["gris"],
  },

  {
    serie: "2",
    nomFR: "alice",
    nomEN: "alice",
    style: ["mimi"],
    race: "koalas",
    caractere: "Normale",
    anniversaire: "19/08",
    numero: "182",
    couleur: ["brun", "blanc", "orange", "jaune"],
  },
  {
    serie: "1",
    nomFR: "calypso",
    nomEN: "yuka",
    style: ["fantaisie", "élégant"],
    race: "koalas",
    caractere: "Arrogante",
    anniversaire: "20/07",
    numero: "071",
    couleur: ["bleu", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "gonzo",
    nomEN: "gonzo",
    style: ["simple", "fantaisie"],
    race: "koalas",
    caractere: "Versatile",
    anniversaire: "13/10",
    numero: "WA-42",
    couleur: ["gris", "blanc", "rose"],
  },
  {
    serie: "1",
    nomFR: "jamy",
    nomEN: "eugene",
    style: ["fantaisie", "magnifique"],
    race: "koalas",
    caractere: "Chic",
    anniversaire: "26/10",
    numero: "080",
    couleur: ["beige", "marron", "brun", "noir"],
  },
  {
    serie: "3",
    nomFR: "kalyptus",
    nomEN: "lyman",
    style: ["simple", "actif"],
    race: "koalas",
    caractere: "Sportif",
    anniversaire: "12/10",
    numero: "281",
    couleur: ["vert", "vert pastel", "jaune pastel"],
  },
  {
    serie: "4",
    nomFR: "koaline",
    nomEN: "sydney",
    style: ["mimi", "simple"],
    race: "koalas",
    caractere: "Normale",
    anniversaire: "21/06",
    numero: "377",
    couleur: ["violet", "blanc"],
  },
  {
    serie: "2",
    nomFR: "koko",
    nomEN: "ozzie",
    style: ["simple", "mimi"],
    race: "koalas",
    caractere: "Paresseux",
    anniversaire: "07/05",
    numero: "120",
    couleur: ["kaki", "gris"],
  },
  {
    serie: "3",
    nomFR: "kolala",
    nomEN: "canberra",
    style: ["actif", "fantaisie"],
    race: "koalas",
    caractere: "Grande soeur",
    anniversaire: "14/05",
    numero: "232",
    couleur: ["orange", "brun", "corail"],
  },
  {
    serie: "5",
    nomFR: "kolette",
    nomEN: "faith",
    style: ["élégant", "mimi"],
    race: "koalas",
    caractere: "Grande soeur",
    anniversaire: "21/03",
    numero: "448",
    couleur: ["orange", "beige", "blanc"],
  },
  {
    serie: "4",
    nomFR: "melba",
    nomEN: "melba",
    style: ["mimi"],
    race: "koalas",
    caractere: "Normale",
    anniversaire: "12/04",
    numero: "341",
    couleur: ["brun", "beige"],
  },

  {
    serie: "5",
    nomFR: "alix",
    nomEN: "sasha",
    style: ["simple", "mimi"],
    race: "lapins",
    caractere: "Paresseux",
    anniversaire: "19/05",
    numero: "433",
    couleur: ["turquoise", "vert", "jaune"],
  },
  {
    serie: "4",
    nomFR: "civet",
    nomEN: "oHare",
    style: ["actif", "fantaisie"],
    race: "lapins",
    caractere: "Chic",
    anniversaire: "24/07",
    numero: "390",
    couleur: ["marron"],
  },

  {
    serie: "1",
    nomFR: "clara",
    nomEN: "bunnie",
    style: ["mimi"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "09/05",
    numero: "087",
    couleur: ["rouge", "jaune pastel", "orange"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "claude",
    nomEN: "claude",
    style: ["simple"],
    race: "lapins",
    caractere: "Paresseux",
    anniversaire: "03/12",
    numero: "WA-27",
    couleur: ["orange", "beige", "brun"],
  },
  {
    serie: "2",
    nomFR: "coco",
    nomEN: "coco",
    style: ["simple", "mimi"],
    race: "lapins",
    caractere: "Normale",
    anniversaire: "01/03",
    numero: "150",
    couleur: ["brun", "beige"],
  },
  {
    serie: "4",
    nomFR: "doc",
    nomEN: "doc",
    style: ["simple", "élégant"],
    race: "lapins",
    caractere: "Paresseux",
    anniversaire: "16/03",
    numero: "372",
    couleur: ["bleu", "brun"],
  },
  {
    serie: "4",
    nomFR: "dorothée",
    nomEN: "dotty",
    style: ["simple", "mimi"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "14/03",
    numero: "335",
    couleur: ["noir", "blanc"],
  },
  {
    serie: "1",
    nomFR: "épicure",
    nomEN: "cole",
    style: ["simple", "mimi"],
    race: "lapins",
    caractere: "Paresseux",
    anniversaire: "10/08",
    numero: "096",
    couleur: ["noir"],
  },
  {
    serie: "2",
    nomFR: "gaby",
    nomEN: "gabi",
    style: ["mimi", "magnifique"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "16/12",
    numero: "156",
    couleur: ["blanc", "brun"],
  },
  {
    serie: "3",
    nomFR: "gaston",
    nomEN: "gaston",
    style: ["simple", "magnifique"],
    race: "lapins",
    caractere: "Versatile",
    anniversaire: "28/10",
    numero: "263",
    couleur: ["jaune", "brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "grignote",
    nomEN: "hopkins",
    style: ["simple", "actif"],
    race: "lapins",
    caractere: "Paresseux",
    anniversaire: "11/03",
    numero: "WA-02",
    couleur: ["bleu"],
  },
  {
    serie: "4",
    nomFR: "grisette",
    nomEN: "mira",
    style: ["actif", "fantaisie"],
    race: "lapins",
    caractere: "Grande soeur",
    anniversaire: "06/07",
    numero: "355",
    couleur: ["jaune", "rouge", "bleu"],
  },
  {
    serie: "1",
    nomFR: "jaeannot",
    nomEN: "snake",
    style: ["actif", "simple"],
    race: "lapins",
    caractere: "Sportif",
    anniversaire: "03/11",
    numero: "055",
    couleur: ["fuchsia", "rose"],
  },
  {
    serie: "3",
    nomFR: "kali",
    nomEN: "genji",
    style: ["élégant", "simple"],
    race: "lapins",
    caractere: "Sportif",
    anniversaire: "21/01",
    numero: "253",
    couleur: ["blanc", "marron", "rose"],
  },
  {
    serie: "3",
    nomFR: "kristine",
    nomEN: "chrissy",
    style: ["mimi"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "28/08",
    numero: "300",
    couleur: ["blanc", "rose"],
  },
  {
    serie: "3",
    nomFR: "nadia",
    nomEN: "pippy",
    style: ["mimi", "simple"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "14/06",
    numero: "267",
    couleur: ["jaune pastel", "bleu"],
  },
  {
    serie: "3",
    nomFR: "nadine",
    nomEN: "francine",
    style: ["élégant", "magnifique"],
    race: "lapins",
    caractere: "Arrogante",
    anniversaire: "22/01",
    numero: "299",
    couleur: ["blanc", "bleu", "turquoise"],
  },
  {
    serie: "2",
    nomFR: "rubis",
    nomEN: "ruby",
    style: ["mimi", "actif"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "25/12",
    numero: "170",
    couleur: ["blanc", "orange"],
  },
  {
    serie: "1",
    nomFR: "sylvette",
    nomEN: "bonbon",
    style: ["mimi", "élégant"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "03/03",
    numero: "049",
    couleur: ["gris", "beige", "brun"],
  },
  {
    serie: "1",
    nomFR: "tiphaine",
    nomEN: "tiffany",
    style: ["magnifique", "fantaisie"],
    race: "lapins",
    caractere: "Arrogante",
    anniversaire: "09/01",
    numero: "030",
    couleur: ["blanc", "rouge"],
  },
  {
    serie: "Sanrio",
    nomFR: "toby",
    nomEN: "toby",
    style: ["mimi", "élégant"],
    race: "lapins",
    caractere: "Chic",
    anniversaire: "10/07",
    numero: "S6",
    couleur: ["jaune", "vert", "orange"],
  },
  {
    serie: "2",
    nomFR: "zoé",
    nomEN: "carmen",
    style: ["élégant", "mimi"],
    race: "lapins",
    caractere: "Vive",
    anniversaire: "06/01",
    numero: "145",
    couleur: ["marron", "blanc"],
  },
  {
    serie: "4",
    nomFR: "aimé",
    nomEN: "mott",
    style: ["actif", "élégant"],
    race: "lions",
    caractere: "Sportif",
    anniversaire: "10/07",
    numero: "320",
    couleur: ["jaune", "jaune pastel", "rouge"],
  },
  {
    serie: "3",
    nomFR: "elvis",
    nomEN: "elvis",
    style: ["magnifique", "élégant"],
    race: "lions",
    caractere: "Versatile",
    anniversaire: "23/07",
    numero: "231",
    couleur: ["jaune", "beige", "brun", "marron"],
  },
  {
    serie: "4",
    nomFR: "hercule",
    nomEN: "rory",
    style: ["simple", "actif"],
    race: "lions",
    caractere: "Sportif",
    anniversaire: "07/08",
    numero: "352",
    couleur: ["orange", "brun", "rouge"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "leandro",
    nomEN: "leopold",
    style: ["élégant", "magnifique"],
    race: "lions",
    caractere: "Chic",
    anniversaire: "14/08",
    numero: "WA-37",
    couleur: ["beige", "vert", "brun"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "léo",
    nomEN: "rex",
    style: ["simple", "mimi"],
    race: "lions",
    caractere: "Paresseux",
    anniversaire: "24/07",
    numero: "WA-15",
    couleur: ["orange", "brun", "marron"],
  },
  {
    serie: "2",
    nomFR: "léonard",
    nomEN: "bud",
    style: ["actif", "simple"],
    race: "lions",
    caractere: "Sportif",
    anniversaire: "08/08",
    numero: "169",
    couleur: ["marron", "orange", "brun"],
  },
  {
    serie: "1",
    nomFR: "léopold",
    nomEN: "lionel",
    style: ["magnifique", "actif"],
    race: "lions",
    caractere: "Chic",
    anniversaire: "29/07",
    numero: "072",
    couleur: ["blanc", "brun"],
  },
  {
    serie: "2",
    nomFR: "blanche",
    nomEN: "whitney",
    style: ["élégant", "fantaisie"],
    race: "loups",
    caractere: "Arrogante",
    anniversaire: "17/09",
    numero: "148",
    couleur: ["blanc", "bleu pastel"],
  },
  {
    serie: "1",
    nomFR: "chef",
    nomEN: "chief",
    style: ["fantaisie", "simple"],
    race: "loups",
    caractere: "Versatile",
    anniversaire: "19/12",
    numero: "086",
    couleur: ["orange", "brun", "blanc"],
  },
  {
    serie: "1",
    nomFR: "gary",
    nomEN: "kyle",
    style: ["magnifique", "fantaisie"],
    race: "loups",
    caractere: "Chic",
    anniversaire: "06/12",
    numero: "024",
    couleur: ["kaki", "marron", "brun"],
  },
  {
    serie: "4",
    nomFR: "lobo",
    nomEN: "lobo",
    style: ["fantaisie", "actif"],
    race: "loups",
    caractere: "Versatile",
    anniversaire: "05/11",
    numero: "382",
    couleur: ["bleu", "blanc", "violet"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "loupiot",
    nomEN: "dobie",
    style: ["simple", "fantaisie"],
    race: "loups",
    caractere: "Versatile",
    anniversaire: "17/02",
    numero: "WA-46",
    couleur: ["vert", "vert pastel", "kaki"],
  },
  {
    serie: "2",
    nomFR: "luppa",
    nomEN: "freya",
    style: ["élégant", "fantaisie"],
    race: "loups",
    caractere: "Arrogante",
    anniversaire: "14/12",
    numero: "196",
    couleur: ["rose", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "marilou",
    nomEN: "skye",
    style: ["mimi"],
    race: "loups",
    caractere: "Normale",
    anniversaire: "24/03",
    numero: "272",
    couleur: ["bleu", "turquoise", "beige"],
  },
  {
    serie: "5",
    nomFR: "monica",
    nomEN: "audie",
    style: ["mimi", "actif"],
    race: "loups",
    caractere: "Vive",
    anniversaire: "31/08",
    numero: "428",
    couleur: ["orange", "beige"],
  },
  {
    serie: "4",
    nomFR: "pierrot",
    nomEN: "fang",
    style: ["simple", "fantaisie"],
    race: "loups",
    caractere: "Versatile",
    anniversaire: "18/12",
    numero: "338",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "viviane",
    nomEN: "vivian",
    style: ["magnifique", "élégant"],
    race: "loups",
    caractere: "Arrogante",
    anniversaire: "26/01",
    numero: "WA-01",
    couleur: ["beige", "gris"],
  },
  {
    serie: "3",
    nomFR: "wolfgang",
    nomEN: "wolfgang",
    style: ["fantaisie", "actif"],
    race: "loups",
    caractere: "Versatile",
    anniversaire: "25/11",
    numero: "255",
    couleur: ["jaune pastel", "bleu"],
  },
  {
    serie: "4",
    nomFR: "aurore",
    nomEN: "aurora",
    style: ["mimi", "élégant"],
    race: "manchots",
    caractere: "Normale",
    anniversaire: "27/01",
    numero: "357",
    couleur: ["noir", "blanc", "gris"],
  },
  {
    serie: "3",
    nomFR: "cube",
    nomEN: "cube",
    style: ["simple", "mimi"],
    race: "manchots",
    caractere: "Paresseux",
    anniversaire: "29/01",
    numero: "286",
    couleur: ["noir", "blanc", "bleu", "jaune"],
  },
  {
    serie: "4",
    nomFR: "émilien",
    nomEN: "tex",
    style: ["fantaisie", "élégant"],
    race: "manchots",
    caractere: "Chic",
    anniversaire: "06/10",
    numero: "340",
    couleur: ["bleu", "gris", "blanc"],
  },
  {
    serie: "3",
    nomFR: "ethan",
    nomEN: "boomer",
    style: ["simple", "fantaisie"],
    race: "manchots",
    caractere: "Paresseux",
    anniversaire: "07/02",
    numero: "289",
    couleur: ["kaki", "vert", "blanc"],
  },
  {
    serie: "3",
    nomFR: "friga",
    nomEN: "friga",
    race: "manchots",
    caractere: "Arrogante",
    anniversaire: "16/10",
    numero: "238",
    couleur: ["rose", "bleu"],
  },
  {
    serie: "2",
    nomFR: "gwen",
    nomEN: "gwen",
    race: "manchots",
    caractere: "Arrogante",
    anniversaire: "23/01",
    numero: "125",
    couleur: ["bleu", "blanc", "violet"],
  },
  {
    serie: "1",
    nomFR: "hervé",
    nomEN: "puck",
    race: "manchots",
    caractere: "Paresseux",
    anniversaire: "21/02",
    numero: "043",
    couleur: ["rose", "violet", "blanc"],
  },
  {
    serie: "2",
    nomFR: "laurie",
    nomEN: "sprinkle",
    race: "manchots",
    caractere: "Vive",
    anniversaire: "20/02",
    numero: "176",
    couleur: ["turquoise", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "miglou",
    nomEN: "wade",
    race: "manchots",
    caractere: "Paresseux",
    anniversaire: "30/10",
    numero: "WA-12",
    couleur: ["blanc", "noir", "gris"],
  },
  {
    serie: "1",
    nomFR: "nora",
    nomEN: "flo",
    race: "manchots",
    caractere: "Grande soeur",
    anniversaire: "02/09",
    numero: "073",
    couleur: ["bleu", "violet", "blanc"],
  },
  {
    serie: "1",
    nomFR: "reynald",
    nomEN: "roald",
    race: "manchots",
    caractere: "Sportif",
    anniversaire: "05/01",
    numero: "098",
    couleur: ["bleu", "blanc"],
  },
  {
    serie: "4",
    nomFR: "urbain",
    nomEN: "iggly",
    race: "manchots",
    caractere: "Sportif",
    anniversaire: "02/11",
    numero: "397",
    couleur: ["blanc", "vert"],
  },
  {
    serie: "2",
    nomFR: "victor",
    nomEN: "hopper",
    race: "manchots",
    caractere: "Versatile",
    anniversaire: "06/04",
    numero: "179",
    couleur: ["noir", "blanc", "orange"],
  },
  {
    serie: "5",
    nomFR: "zinzin",
    nomEN: "chabwick",
    race: "manchots",
    caractere: "Paresseux",
    anniversaire: "24/12",
    numero: "441",
    couleur: ["bleu", "blanc"],
  },
  {
    serie: "3",
    nomFR: "bêêtty",
    nomEN: "baabara",
    race: "moutons",
    caractere: "Arrogante",
    anniversaire: "28/03",
    numero: "292",
    couleur: ["marron", "bleu pastel"],
  },
  {
    serie: "1",
    nomFR: "bérénice",
    nomEN: "eunice",
    race: "moutons",
    caractere: "Normale",
    anniversaire: "03/04",
    numero: "081",
    couleur: ["rose", "noir"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "bigoudi",
    nomEN: "stella",
    race: "moutons",
    caractere: "Normale",
    anniversaire: "09/04",
    numero: "WA-07",
    couleur: ["rose", "fuchsia", "rose"],
  },
  {
    serie: "5",
    nomFR: "bouloche",
    nomEN: "dom",
    race: "moutons",
    caractere: "Sportif",
    anniversaire: "18/03",
    numero: "427",
    couleur: ["blanc", "rouge", "rose"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "cashmir",
    nomEN: "cashmere",
    race: "moutons",
    caractere: "Arrogante",
    anniversaire: "02/04",
    numero: "WA-39",
    couleur: ["kaki", "vert", "orange", "blanc", "bleu pastel"],
  },
  {
    serie: "1",
    nomFR: "charlène",
    nomEN: "muffy",
    race: "moutons",
    caractere: "Grande soeur",
    anniversaire: "14/02",
    numero: "091",
    couleur: ["noir", "blanc", "violet"],
  },
  {
    serie: "4",
    nomFR: "clarabêl",
    nomEN: "frita",
    race: "moutons",
    caractere: "Grande soeur",
    anniversaire: "16/07",
    numero: "339",
    couleur: ["orange", "brun"],
  },
  {
    serie: "Sanrio",
    nomFR: "étoile",
    nomEN: "etoile",
    race: "moutons",
    caractere: "Normale",
    anniversaire: "25/12",
    numero: "S3",
    couleur: ["rose", "violet"],
  },
  {
    serie: "2",
    nomFR: "hélaine",
    nomEN: "vesta",
    race: "moutons",
    caractere: "Normale",
    anniversaire: "16/04",
    numero: "190",
    couleur: ["jaune pastel", "noir"],
  },
  {
    serie: "2",
    nomFR: "karen",
    nomEN: "wendy",
    race: "moutons",
    caractere: "Vive",
    anniversaire: "15/08",
    numero: "152",
    couleur: ["bleu", "turquoise", "orange", "brun"],
  },
  {
    serie: "1",
    nomFR: "maï",
    nomEN: "willow",
    race: "moutons",
    caractere: "Arrogante",
    anniversaire: "26/11",
    numero: "097",
    couleur: ["jaune", "violet"],
  },
  {
    serie: "4",
    nomFR: "pietro",
    nomEN: "pietro",
    race: "moutons",
    caractere: "Chic",
    anniversaire: "19/04",
    numero: "356",
    couleur: ["blanc", "turquoise", "multicolore"],
  },
  {
    serie: "2",
    nomFR: "sélène",
    nomEN: "timbra",
    race: "moutons",
    caractere: "Arrogante",
    anniversaire: "21/10",
    numero: "158",
    couleur: ["orange", "brun"],
  },
  {
    serie: "3",
    nomFR: "tonton",
    nomEN: "curlos",
    race: "moutons",
    caractere: "Chic",
    anniversaire: "08/05",
    numero: "271",
    couleur: ["marron", "kaki"],
  },
  {
    serie: "5",
    nomFR: "boumboum",
    nomEN: "ace",
    race: "oiseaux",
    caractere: "Sportif",
    anniversaire: "11/08",
    numero: "443",
    couleur: ["jaune pastel", "bleu", "orange"],
  },
  {
    serie: "2",
    nomFR: "condor",
    nomEN: "lucha",
    race: "oiseaux",
    caractere: "Chic",
    anniversaire: "12/12",
    numero: "122",
    couleur: ["rouge", "blanc", "gris"],
  },
  {
    serie: "3",
    nomFR: "darius",
    nomEN: "sparro",
    race: "oiseaux",
    caractere: "Sportif",
    anniversaire: "20/11",
    numero: "291",
    couleur: ["jaune pastel", "marron", "noir"],
  },
  {
    serie: "2",
    nomFR: "gérard",
    nomEN: "jay",
    race: "oiseaux",
    caractere: "Sportif",
    anniversaire: "17/07",
    numero: "175",
    couleur: ["rouge", "bleu", "blanc"],
  },
  {
    serie: "1",
    nomFR: "gilbert",
    nomEN: "jitters",
    race: "oiseaux",
    caractere: "Sportif",
    anniversaire: "02/02",
    numero: "039",
    couleur: ["vert", "jaune", "bleu"],
  },
  {
    serie: "4",
    nomFR: "jacky",
    nomEN: "jacques",
    race: "oiseaux",
    caractere: "Chic",
    anniversaire: "22/06",
    numero: "370",
    couleur: ["bleu", "vert"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "jacob",
    nomEN: "jacob",
    race: "oiseaux",
    caractere: "Paresseux",
    anniversaire: "24/08",
    numero: "WA-18",
    couleur: ["blanc", "jaune", "rouge", "vert"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "maréchal",
    nomEN: "admiral",
    race: "oiseaux",
    caractere: "Versatile",
    anniversaire: "27/01",
    numero: "WA-32",
    couleur: ["blanc", "vert", "jaune", "orange"],
  },
  {
    serie: "1",
    nomFR: "michèle",
    nomEN: "midge",
    race: "oiseaux",
    caractere: "Normale",
    anniversaire: "12/03",
    numero: "065",
    couleur: ["fuchsia", "blanc"],
  },
  {
    serie: "3",
    nomFR: "miguel",
    nomEN: "anchovy",
    race: "oiseaux",
    caractere: "Paresseux",
    anniversaire: "04/03",
    numero: "219",
    couleur: ["marron", "brun", "blanc"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "neige",
    nomEN: "piper",
    race: "oiseaux",
    caractere: "Vive",
    anniversaire: "18/04",
    numero: "WA-04",
    couleur: ["blanc"],
  },
  {
    serie: "2",
    nomFR: "pec",
    nomEN: "peck",
    race: "oiseaux",
    caractere: "Sportif",
    anniversaire: "25/07",
    numero: "142",
    couleur: ["marron", "gris", "blanc"],
  },
  {
    serie: "4",
    nomFR: "robie",
    nomEN: "robin",
    race: "oiseaux",
    caractere: "Arrogante",
    anniversaire: "04/12",
    numero: "400",
    couleur: ["bleu", "blanc", "orange"],
  },
  {
    serie: "4",
    nomFR: "titi",
    nomEN: "twiggy",
    race: "oiseaux",
    caractere: "Vive",
    anniversaire: "13/07",
    numero: "399",
    couleur: ["jaune", "vert"],
  },
  {
    serie: "5",
    nomFR: "candy",
    nomEN: "megan",
    race: "ours",
    caractere: "Normale",
    anniversaire: "13/03",
    numero: "426",
    couleur: ["violet"],
  },
  {
    serie: "4",
    nomFR: "chulin",
    nomEN: "chow",
    race: "ours",
    caractere: "Versatile",
    anniversaire: "22/07",
    numero: "368",
    couleur: ["rose", "noir"],
  },
  {
    serie: "1",
    nomFR: "curt",
    nomEN: "curt",
    race: "ours",
    caractere: "Versatile",
    anniversaire: "01/07",
    numero: "020",
    couleur: ["gris", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "eustache",
    nomEN: "beardo",
    race: "ours",
    caractere: "Chic",
    anniversaire: "27/09",
    numero: "249",
    couleur: ["turquoise", "marron"],
  },
  {
    serie: "4",
    nomFR: "grizzly",
    nomEN: "grizzly",
    race: "ours",
    caractere: "Versatile",
    anniversaire: "31/07",
    numero: "394",
    couleur: ["marron", "beige"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "isaac",
    nomEN: "ike",
    race: "ours",
    caractere: "Versatile",
    anniversaire: "16/05",
    numero: "WA-49",
    couleur: ["jaune pastel", "marron", "orange"],
  },
  {
    serie: "3",
    nomFR: "klaus",
    nomEN: "klaus",
    race: "ours",
    caractere: "Chic",
    anniversaire: "31/03",
    numero: "257",
    couleur: ["turquoise", "bleu"],
  },
  {
    serie: "1",
    nomFR: "nathan",
    nomEN: "nate",
    race: "ours",
    caractere: "Paresseux",
    anniversaire: "16/08",
    numero: "059",
    couleur: ["orange", "beige"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "oursula",
    nomEN: "ursula",
    race: "ours",
    caractere: "Grande soeur",
    anniversaire: "16/01",
    numero: "WA-17",
    couleur: ["rose", "jaune pastel"],
  },
  {
    serie: "2",
    nomFR: "ronchon",
    nomEN: "groucho",
    race: "ours",
    caractere: "Versatile",
    anniversaire: "23/10",
    numero: "151",
    couleur: ["bleu", "beige"],
  },
  {
    serie: "4",
    nomFR: "rosine",
    nomEN: "pinky",
    race: "ours",
    caractere: "Vive",
    anniversaire: "09/09",
    numero: "319",
    couleur: ["fuchsia", "violet", "beige"],
  },
  {
    serie: "2",
    nomFR: "teddy",
    nomEN: "teddy",
    race: "ours",
    caractere: "Sportif",
    anniversaire: "26/09",
    numero: "161",
    couleur: ["brun", "beige"],
  },
  {
    serie: "1",
    nomFR: "tutu",
    nomEN: "tutu",
    race: "ours",
    caractere: "Vive",
    anniversaire: "15/09",
    numero: "061",
    couleur: ["beige", "rose"],
  },
  {
    serie: "3",
    nomFR: "wendy",
    nomEN: "paula",
    race: "ours",
    caractere: "Grande soeur",
    anniversaire: "22/03",
    numero: "224",
    couleur: ["brun", "beige"],
  },
  {
    serie: "2",
    nomFR: "zabou",
    nomEN: "charlise",
    race: "ours",
    caractere: "Grande soeur",
    anniversaire: "17/04",
    numero: "186",
    couleur: ["vert"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "agnès",
    nomEN: "june",
    race: "oursons",
    caractere: "Normale",
    anniversaire: "21/05",
    numero: "WA-03",
    couleur: ["beige", "brun"],
  },
  {
    serie: "3",
    nomFR: "bill",
    nomEN: "kody",
    race: "oursons",
    caractere: "Sportif",
    anniversaire: "28/09",
    numero: "221",
    couleur: ["bleu"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "eddie",
    nomEN: "murphy",
    race: "oursons",
    caractere: "Versatile",
    anniversaire: "29/12",
    numero: "WA-24",
    couleur: ["vert"],
  },
  {
    serie: "1",
    nomFR: "gradub",
    nomEN: "pudge",
    race: "oursons",
    caractere: "Paresseux",
    anniversaire: "11/06",
    numero: "064",
    couleur: ["orange"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "grisa",
    nomEN: "olive",
    race: "oursons",
    caractere: "Normale",
    anniversaire: "12/07",
    numero: "WA-45",
    couleur: ["gris"],
  },
  {
    serie: "5",
    nomFR: "laura",
    nomEN: "judy",
    race: "oursons",
    caractere: "Arrogante",
    anniversaire: "10/03",
    numero: "430",
    couleur: ["cute", "bleu pastel", "violet", "violet pastel"],
  },
  {
    serie: "3",
    nomFR: "léa",
    nomEN: "maple",
    race: "oursons",
    caractere: "Normale",
    anniversaire: "15/06",
    numero: "294",
    couleur: ["brun", "beige"],
  },
  {
    serie: "4",
    nomFR: "manu",
    nomEN: "barold",
    race: "oursons",
    caractere: "Paresseux",
    anniversaire: "02/03",
    numero: "378",
    couleur: ["gris"],
  },
  {
    serie: "Sanrio",
    nomFR: "marty",
    nomEN: "marty",
    race: "oursons",
    caractere: "Paresseux",
    anniversaire: "16/04",
    numero: "S2",
    couleur: ["jaune"],
  },
  {
    serie: "4",
    nomFR: "miro",
    nomEN: "stitches",
    race: "oursons",
    caractere: "Paresseux",
    anniversaire: "11/02",
    numero: "318",
    couleur: ["orange", "violet", "vert", "rouge", "bleu", "multicolore"],
  },
  {
    serie: "1",
    nomFR: "myrtille",
    nomEN: "bluebear",
    race: "oursons",
    caractere: "Vive",
    anniversaire: "24/06",
    numero: "032",
    couleur: ["turquoise", "bleu"],
  },
  {
    serie: "2",
    nomFR: "pauline",
    nomEN: "pokoe",
    race: "oursons",
    caractere: "Normale",
    anniversaire: "18/05",
    numero: "160",
    couleur: ["jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "placide",
    nomEN: "chester",
    race: "oursons",
    caractere: "Paresseux",
    anniversaire: "06/08",
    numero: "251",
    couleur: ["blanc", "bleu", "jaune pastel"],
  },
  {
    serie: "1",
    nomFR: "rosalie",
    nomEN: "cheri",
    race: "oursons",
    caractere: "Vive",
    anniversaire: "17/03",
    numero: "023",
    couleur: ["rouge", "beige"],
  },
  {
    serie: "2",
    nomFR: "théo",
    nomEN: "poncho",
    race: "oursons",
    caractere: "Sportif",
    anniversaire: "02/01",
    numero: "118",
    couleur: ["bleu"],
  },
  {
    serie: "4",
    nomFR: "vanessa",
    nomEN: "tammy",
    race: "oursons",
    caractere: "Grande soeur",
    anniversaire: "23/06",
    numero: "347",
    couleur: ["jaune"],
  },
  {
    serie: "2",
    nomFR: "vladimir",
    nomEN: "vladimir",
    race: "oursons",
    caractere: "Versatile",
    anniversaire: "02/08",
    numero: "132",
    couleur: ["fuchsia", "rose"],
  },
  {
    serie: "2",
    nomFR: "dimitri",
    nomEN: "benedict",
    race: "poulets",
    caractere: "Paresseux",
    anniversaire: "10/10",
    numero: "171",
    couleur: ["rouge", "blanc"],
  },
  {
    serie: "3",
    nomFR: "eva",
    nomEN: "ava",
    race: "poulets",
    caractere: "Normale",
    anniversaire: "28/04",
    numero: "250",
    couleur: ["brun", "beige", "jaune"],
  },
  {
    serie: "2",
    nomFR: "herbert",
    nomEN: "egbert",
    race: "poulets",
    caractere: "Paresseux",
    anniversaire: "14/10",
    numero: "136",
    couleur: ["jaune"],
  },
  {
    serie: "4",
    nomFR: "jo",
    nomEN: "broffina",
    race: "poulets",
    caractere: "Arrogante",
    anniversaire: "24/10",
    numero: "329",
    couleur: ["brun", "orange"],
  },
  {
    serie: "3",
    nomFR: "ken",
    nomEN: "ken",
    race: "poulets",
    caractere: "Chic",
    anniversaire: "23/12",
    numero: "225",
    couleur: ["noir", "bleu"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "poulette",
    nomEN: "plucky",
    race: "poulets",
    caractere: "Grande soeur",
    anniversaire: "12/10",
    numero: "WA-25",
    couleur: ["marron", "brun"],
  },
  {
    serie: "1",
    nomFR: "pouli",
    nomEN: "goose",
    race: "poulets",
    caractere: "Sportif",
    anniversaire: "04/10",
    numero: "082",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "4",
    nomFR: "sonya",
    nomEN: "becky",
    race: "poulets",
    caractere: "Arrogante",
    anniversaire: "09/12",
    numero: "375",
    couleur: ["violet", "violet pastel"],
  },
  {
    serie: "1",
    nomFR: "wolfram",
    nomEN: "knox",
    race: "poulets",
    caractere: "Versatile",
    anniversaire: "23/11",
    numero: "047",
    couleur: ["gris", "jaune"],
  },
  {
    serie: "3",
    nomFR: "marina",
    nomEN: "marina",
    race: "poulpes",
    caractere: "Normale",
    anniversaire: "26/06",
    numero: "234",
    couleur: ["rose", "fuchsia"],
  },
  {
    serie: "4",
    nomFR: "marvin",
    nomEN: "zucker",
    race: "poulpes",
    caractere: "Paresseux",
    anniversaire: "08/03",
    numero: "364",
    couleur: ["brun", "beige", "rouge", "marron"],
  },
  {
    serie: "1",
    nomFR: "octave",
    nomEN: "octavian",
    race: "poulpes",
    caractere: "Versatile",
    anniversaire: "20/09",
    numero: "045",
    couleur: ["rouge"],
  },
  {
    serie: "5",
    nomFR: "octoborg",
    nomEN: "cephalobot",
    race: "poulpes",
    caractere: "Chic",
    anniversaire: "01/04",
    numero: "439",
    couleur: ["gris"],
  },
  {
    serie: "5",
    nomFR: "azalée",
    nomEN: "azalea",
    race: "rhinocéros",
    caractere: "Arrogante",
    anniversaire: "18/12",
    numero: "446",
    couleur: ["turquoise"],
  },
  {
    serie: "4",
    nomFR: "ben",
    nomEN: "tank",
    race: "rhinocéros",
    caractere: "Sportif",
    anniversaire: "06/05",
    numero: "374",
    couleur: ["gris"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "cornio",
    nomEN: "hornsby",
    race: "rhinocéros",
    caractere: "Paresseux",
    anniversaire: "20/03",
    numero: "WA-06",
    couleur: ["bleu"],
  },
  {
    serie: "3",
    nomFR: "patty",
    nomEN: "merengue",
    race: "rhinocéros",
    caractere: "Normale",
    anniversaire: "19/03",
    numero: "285",
    couleur: ["rose", "blanc"],
  },
  {
    serie: "2",
    nomFR: "renée",
    nomEN: "rhonda",
    race: "rhinocéros",
    caractere: "Normale",
    anniversaire: "24/01",
    numero: "154",
    couleur: ["beige"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "rhino",
    nomEN: "spike",
    race: "rhinocéros",
    caractere: "Versatile",
    anniversaire: "17/06",
    numero: "WA-38",
    couleur: ["orange", "brun"],
  },
  {
    serie: "1",
    nomFR: "rina",
    nomEN: "renee",
    race: "rhinocéros",
    caractere: "Grande soeur",
    anniversaire: "28/05",
    numero: "026",
    couleur: ["violet"],
  },
  {
    serie: "4",
    nomFR: "élise",
    nomEN: "elise",
    race: "singes",
    caractere: "Arrogante",
    anniversaire: "21/03",
    numero: "353",
    couleur: ["brun", "beige", "kaki"],
  },
  {
    serie: "3",
    nomFR: "lili",
    nomEN: "tammi",
    race: "singes",
    caractere: "Vive",
    anniversaire: "02/04",
    numero: "260",
    couleur: ["jaune", "jaune pastel"],
  },
  {
    serie: "3",
    nomFR: "lourant",
    nomEN: "monty",
    race: "singes",
    caractere: "Versatile",
    anniversaire: "07/12",
    numero: "277",
    couleur: ["gris", "beige"],
  },
  {
    serie: "1",
    nomFR: "luna",
    nomEN: "shari",
    race: "singes",
    caractere: "Grande soeur",
    anniversaire: "10/04",
    numero: "044",
    couleur: ["gris", "blanc"],
  },
  {
    serie: "1",
    nomFR: "magogo",
    nomEN: "deli",
    race: "singes",
    caractere: "Paresseux",
    anniversaire: "24/05",
    numero: "035",
    couleur: ["beige", "brun"],
  },
  {
    serie: "2",
    nomFR: "mireille",
    nomEN: "nana",
    race: "singes",
    caractere: "Normale",
    anniversaire: "23/08",
    numero: "141",
    couleur: ["rose", "violet", "beige"],
  },
  {
    serie: "2",
    nomFR: "rudy",
    nomEN: "flip",
    race: "singes",
    caractere: "Sportif",
    anniversaire: "21/11",
    numero: "177",
    couleur: ["orange", "brun", "beige"],
  },
  {
    serie: "4",
    nomFR: "simon",
    nomEN: "simon",
    race: "singes",
    caractere: "Paresseux",
    anniversaire: "19/01",
    numero: "396",
    couleur: ["brun"],
  },
  {
    serie: "5",
    nomFR: "tiansheng",
    nomEN: "tiansheng",
    race: "singes",
    caractere: "Sportif",
    anniversaire: "18/08",
    numero: "435",
    couleur: ["orange", "blanc"],
  },
  {
    serie: "2",
    nomFR: "annie",
    nomEN: "annicotti",
    race: "souris",
    caractere: "Vive",
    anniversaire: "24/02",
    numero: "184",
    couleur: ["vert"],
  },
  {
    serie: "1",
    nomFR: "belle",
    nomEN: "bella",
    race: "souris",
    caractere: "Vive",
    anniversaire: "28/12",
    numero: "069",
    couleur: ["blanc", "rose", "gris"],
  },
  {
    serie: "3",
    nomFR: "dora",
    nomEN: "dora",
    race: "souris",
    caractere: "Normale",
    anniversaire: "18/02",
    numero: "278",
    couleur: ["blanc", "bleu"],
  },
  {
    serie: "3",
    nomFR: "greta",
    nomEN: "greta",
    race: "souris",
    caractere: "Arrogante",
    anniversaire: "05/09",
    numero: "254",
    couleur: ["blanc", "bleu", "rouge"],
  },
  {
    serie: "1",
    nomFR: "gruyère",
    nomEN: "limberg",
    race: "souris",
    caractere: "Versatile",
    anniversaire: "17/10",
    numero: "053",
    couleur: ["orange"],
  },
  {
    serie: "2",
    nomFR: "joachim",
    nomEN: "moose",
    race: "souris",
    caractere: "Sportif",
    anniversaire: "13/09",
    numero: "157",
    couleur: ["bleu", "marron"],
  },
  {
    serie: "4",
    nomFR: "marcel",
    nomEN: "rod",
    race: "souris",
    caractere: "Sportif",
    anniversaire: "14/08",
    numero: "360",
    couleur: ["violet"],
  },
  {
    serie: "4",
    nomFR: "missy",
    nomEN: "penelope",
    race: "souris",
    caractere: "Vive",
    anniversaire: "05/02",
    numero: "327",
    couleur: ["kaki", "vert pastel"],
  },
  {
    serie: "3",
    nomFR: "mozzar",
    nomEN: "chadder",
    race: "souris",
    caractere: "Chic",
    anniversaire: "15/12",
    numero: "284",
    couleur: ["orange", "jaune"],
  },
  {
    serie: "3",
    nomFR: "quenotte",
    nomEN: "bree",
    race: "souris",
    caractere: "Arrogante",
    anniversaire: "07/07",
    numero: "269",
    couleur: ["gris", "violet pastel", "rose"],
  },
  {
    serie: "2",
    nomFR: "sabrina",
    nomEN: "bettina",
    race: "souris",
    caractere: "Normale",
    anniversaire: "12/06",
    numero: "174",
    couleur: ["orange", "jaune"],
  },
  {
    serie: "1",
    nomFR: "samson",
    nomEN: "samson",
    race: "souris",
    caractere: "Sportif",
    anniversaire: "05/07",
    numero: "060",
    couleur: ["turquoise", "gris"],
  },
  {
    serie: "5",
    nomFR: "shimi",
    nomEN: "petri",
    race: "souris",
    caractere: "Arrogante",
    anniversaire: "23/10",
    numero: "438",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "4",
    nomFR: "sourizzi",
    nomEN: "rizzo",
    race: "souris",
    caractere: "Versatile",
    anniversaire: "17/01",
    numero: "376",
    couleur: ["bleu"],
  },
  {
    serie: "2",
    nomFR: "steven",
    nomEN: "broccolo",
    race: "souris",
    caractere: "Paresseux",
    anniversaire: "30/06",
    numero: "149",
    couleur: ["bleu"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "sucrette",
    nomEN: "candi",
    race: "souris",
    caractere: "Vive",
    anniversaire: "13/04",
    numero: "WA-36",
    couleur: ["rose", "fuchsia"],
  },
  {
    serie: "4",
    nomFR: "angus",
    nomEN: "angus",
    race: "taureaux",
    caractere: "Versatile",
    anniversaire: "30/04",
    numero: "398",
    couleur: ["brun", "beige"],
  },
  {
    serie: "2",
    nomFR: "arnold",
    nomEN: "coach",
    race: "taureaux",
    caractere: "Sportif",
    anniversaire: "29/04",
    numero: "126",
    couleur: ["jaune", "gris"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "beubeu",
    nomEN: "stu",
    race: "taureaux",
    caractere: "Paresseux",
    anniversaire: "20/04",
    numero: "WA-16",
    couleur: ["bleu"],
  },
  {
    serie: "3",
    nomFR: "flèche",
    nomEN: "rodeo",
    race: "taureaux",
    caractere: "Paresseux",
    anniversaire: "29/10",
    numero: "227",
    couleur: ["gris"],
  },
  {
    serie: "1",
    nomFR: "steakos",
    nomEN: "t-Bone",
    race: "taureaux",
    caractere: "Versatile",
    anniversaire: "20/05",
    numero: "062",
    couleur: ["gris", "bleu"],
  },
  {
    serie: "2",
    nomFR: "toto",
    nomEN: "vic",
    race: "taureaux",
    caractere: "Versatile",
    anniversaire: "29/12",
    numero: "187",
    couleur: ["brun", "beige"],
  },
  {
    serie: "1",
    nomFR: "bengale",
    nomEN: "bangle",
    race: "tigres",
    caractere: "Vive",
    anniversaire: "27/08",
    numero: "056",
    couleur: ["marron", "jaune"],
  },
  {
    serie: "1",
    nomFR: "dolph",
    nomEN: "leonardo",
    race: "tigres",
    caractere: "Sportif",
    anniversaire: "15/05",
    numero: "022",
    couleur: ["jaune", "marron"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "jeff",
    nomEN: "tybalt",
    race: "tigres",
    caractere: "Sportif",
    anniversaire: "19/08",
    numero: "WA-08",
    couleur: ["jaune", "marron"],
  },
  {
    serie: "4",
    nomFR: "marito",
    nomEN: "rowan",
    race: "tigres",
    caractere: "Sportif",
    anniversaire: "28/08",
    numero: "387",
    couleur: ["orange", "blanc"],
  },
  {
    serie: "2",
    nomFR: "noémie",
    nomEN: "bianca",
    race: "tigres",
    caractere: "Vive",
    anniversaire: "13/12",
    numero: "164",
    couleur: ["bleu pastel", "bleu"],
  },
  {
    serie: "3",
    nomFR: "ralf",
    nomEN: "rolf",
    race: "tigres",
    caractere: "Versatile",
    anniversaire: "22/08",
    numero: "293",
    couleur: ["blanc", "gris"],
  },
  {
    serie: "3",
    nomFR: "vanina",
    nomEN: "claudia",
    race: "tigres",
    caractere: "Arrogante",
    anniversaire: "22/11",
    numero: "287",
    couleur: ["fuchsia", "rose", "violet", "bleu"],
  },
  {
    serie: "4",
    nomFR: "maiko",
    nomEN: "naomi",
    race: "vaches",
    caractere: "Arrogante",
    anniversaire: "28/02",
    numero: "345",
    couleur: ["turquoise", "blanc", "bleu"],
  },
  {
    serie: "1",
    nomFR: "margaux",
    nomEN: "patty",
    race: "vaches",
    caractere: "Vive",
    anniversaire: "10/05",
    numero: "038",
    couleur: ["beige", "marron"],
  },
  {
    serie: "Welcome Amiibo",
    nomFR: "norma",
    nomEN: "norma",
    race: "vaches",
    caractere: "Normale",
    anniversaire: "20/09",
    numero: "WA-41",
    couleur: ["beige", "rose"],
  },
  {
    serie: "2",
    nomFR: "valé",
    nomEN: "tipper",
    race: "vaches",
    caractere: "Arrogante",
    anniversaire: "25/08",
    numero: "129",
    couleur: ["blanc", "gris", "rose"],
  },
];
